### ISSUE TITLE
Provide a means to open lists of URLs in browser windows

### ISSUE THREAD

**Issue by dotjay** [ttscoff/bunch#105]
I've tried a few variations on the following to allow groups of tabs to be opened in new browser windows, which helps when a Bunch is triggered while a browser is already open, and helps keep projects separated. 

```
Firefox ~1
- {@n}
- (pause 1)
- http://example.com/
- http://example.com/
- http://example.com/
- {@n}
- (pause 1)
- http://duckduckgo.com/
- http://duckduckgo.com/
- http://duckduckgo.com/
```

Expectation:
Two new Firefox windows open, one with the first 3 URLs and a second with the latter 3 URLs opened in tabs.

Current behaviour:
Even if I set `sequential` to true or toggle off the "Launch items in parallel" preferences setting, the URLs are opened before the browser commands have fired, so the URLs all open in the foremost browser window before then opening two new (empty) browser windows.

**Comment by dotjay** [comment]
Incidentally, I also note that the documentation on [Delayed Launch](https://bunchapp.co/docs/bunch-files/delay/) uses two different commands: `(pause 5)` and `(delay 5)`.

I'm guessing that the two are interchangeable?

**Comment by ttscoff** [comment]
Does it make any difference if you put the pause _before_ the key 
command? Even in sequential mode it's basically a race to see what the 
app responds to first. Sending a bunch of urls and a key command at the 
same time will likely be processed urls first, then key commands.

-Brett

**Comment by ttscoff** [comment]
Yeah, they both work.

**Comment by dotjay** [comment]
> Does it make any difference if you put the pause _before_ the key command? Even in sequential mode it's basically a race to see what the app responds to first. Sending a bunch of urls and a key command at the same time will likely be processed urls first, then key commands.

Thanks, Brett. I'm afraid not. Below are the things I've tried.

I had a similar requirement for Finder windows, so I came up with [BunchFinder](https://github.com/dotjay/BunchFinder) as an extension calling an AppleScript. I might see if I can do something similar for browser windows.

```
---
title: Firefox tabs
sequential: true
---


## Approach 1, URLs in list
## Does not work in Bunch 1.4; opens all URLs and then two new browser windows
#%Firefox ~1
#- {@n}
#- (pause 1)
#- http://example.com/
#- http://example.com/
#- http://example.com/
#- {@n}
#- (pause 1)
#- http://duckduckgo.com/
#- http://duckduckgo.com/
#- http://duckduckgo.com/


## Approach 2, URLs without list items
## Does not work in Bunch 1.4; opens the first 3 tabs, a new browser window, and URLs 4-6 in their own windows
#
#%Firefox
#- {@n}
#- (pause 1)
#http://example.com/
#http://example.com/
#http://example.com/
#
#%Firefox
#- {@n}
#- (pause 1)
#http://duckduckgo.com/
#http://duckduckgo.com/
#http://duckduckgo.com/


## Approach 3, pause before the key commands
## Does not work in Bunch 1.4; opens all URLs and then two new browser windows
#%Firefox
#- (pause 1)
#- {@n}
#- http://example.com/
#- http://example.com/
#- http://example.com/
#- (pause 1)
#- {@n}
#- http://duckduckgo.com/
#- http://duckduckgo.com/
#- http://duckduckgo.com/
```

**Comment by dotjay** [comment]
Ah ha! This approach works as a solution, which I guess I might be able to turn into a snippet.

```
## Approach 4, typing URLs, no pauses
## Works
%Firefox
- {@n "http://example.com/" ↩}
- {@t "http://example.com/" ↩}
- {@t "http://example.com/" ↩}
- {@n "http://duckduckgo.com/" ↩}
- {@t "http://duckduckgo.com/" ↩}
- {@t "http://duckduckgo.com/" ↩}
```
