### ISSUE TITLE
Toggled Bunches do not open after switching "Toggle Bunches" behaviour

### ISSUE THREAD

**Issue by dotjay** [ttscoff/bunch#106]
Steps to reproduce:
- Start with "Toggle Bunches" mode on
- Toggle a Bunch to open it
- Switch "Toggle Bunches" mode off
- Try to open the same Bunch again

I guess this is very much an edge case, but while running some test Bunches I've cooked up, I switched behaviours and found that my test bunch would no longer open at all. It seems that an "on" Bunch stays "on" and will not therefore open (or close I suspect) when working with "Toggle Bunches" mode off.

**Comment by ttscoff** [comment]
Yeah, once a Bunch is marked as "open," it would prevent it from opening 
again. I'll add a check for current mode and override that if toggle 
turns off. Thanks for the report.

-Brett

**Comment by ttscoff** [comment]
This should be fixed in the latest version (1.4.3).
