### ISSUE TITLE
Bunch hang on interactive snippet with delay

### ISSUE THREAD

**Issue by kotfu** [ttscoff/bunch#121]
It's non-deterministic (meaning it doesn't happen every time), but using Bunch 1.4.3 (β116) on both an M1 Macbook Air with macOS 11.5 and a hackintosh with macOS 10.15.7, I can frequently get Bunch.app to hang and burn 100% CPU.

Use the following bunch file:
```
---
toggles: false
---

#
# a test of snippets

$ say in the bunch

<<#Snippet ?"Open Snippet?" ~3

___

###[Snippet]

$ say in the section fragment
```

When you get the dialog to open the snippet, either press return or escape. This
regularly causes a beachball that Bunch.app never recovers from.

Another observation, which may or may not be related: in the cases that bunch doesn't hang, I never hear "in the bunch" until I either confirm or dismiss the dialog.

I also note that if you remove `~3` from the end of the snippet, everything appears to work just fine.

**Comment by ttscoff** [comment]
I'm not getting any hangs repeatedly running this Bunch. I don't suppose anything shows up in Console when it happens? The fact that removing the delay fixes it for you might indicate a threading issue, so I'll see if I can find anything in there that looks off.

> Another observation, which may or may not be related: in the cases that bunch doesn't hang, I never hear "in the bunch" until I either confirm or dismiss the dialog.

Dialogs are run before any actual processing of Bunch items. Basically, all of the parts of a Bunch which could change (dialogs, conditionals) are resolved before processing the Bunch. So if there's an optional snippet, it will either be confirmed or removed when opening, and then the entire Bunch will be processed either with or without it. So the behavior you're seeing is correct.

**Comment by kotfu** [comment]
Here's a hang generated today when I pressed escape in the dialog. Debug level 4. Local time 16:27. Nothing interesting to me in the log, other than that it logged that I pushed escape (the `---> NO`) but that it didn't get far enough to make the dialog go away (screenshot of what the dialog looked like when hung shown below). Activity monitor screenie shown as well in case that's helpful.

[com.brettterpstra.Bunch 2021-07-25--23-46-33-633.log](https://github.com/ttscoff/bunch/files/6881549/com.brettterpstra.Bunch.2021-07-25--23-46-33-633.log)
<img width="532" alt="Screen Shot 2021-07-26 at 4 28 06 PM" src="https://user-images.githubusercontent.com/218536/127067354-4fe1c46d-d1e2-4b5c-b397-6e8d36c9be73.png">
<img width="944" alt="Screen Shot 2021-07-26 at 4 29 11 PM" src="https://user-images.githubusercontent.com/218536/127067359-81565a26-668e-40a1-8d1e-f453627522e9.png">

**Comment by ttscoff** [comment]
Yeah, I didn't expect the Bunch log to show much in this case. I'd be more interested in what's happening in system.log (the main window in Console), or in any spin reports (in the sidebar) generated by Bunch.

And this is happening on both of your machines, running different processors and OS versions? This is really weird, would love to track it down.

**Comment by kotfu** [comment]
Tried to reproduce this again yesterday, couldn't do it. I'll keep after it and see if I can get you better logs.

**Comment by kotfu** [comment]
Over the last couple of weeks I have been unable to make this happen again on either of my computers. I suggest closing for now until I can reproduce reliably.
