### ISSUE TITLE
Bunch can't open files from command line using `open`

### ISSUE THREAD

**Issue by kotfu** [ttscoff/bunch#127]
From the command line:
```
$ open -a Bunch MyBunchFile.bunch
```

I receive the following error message: 'The document “SnippetMaster.bunch” could not be opened. Bunch cannot open files in the “Bunch File” format.'

The hard decision will be what to have Bunch.app do when you open a file, maybe toggle the bunch?

There is a work around: you can accomplish the same thing by doing:
```
$ open x-bunch://toggle/MyBunchFile
```

**Comment by ttscoff** [comment]
I don't consider this a bug, the URL scheme is much more capable than opening directly. As you state, using `open -a` Bunch doesn't know exactly what to do with the file and the results would be unpredictable. Using the url handler means you can control which action to perform, pass additional arguments and variables, and even process a Bunch as a snippet or a snippet as a Bunch. It's just much more robust.

**Comment by kotfu** [comment]
I agree. Is there any way to change the error message, or does that come from MacOS? It would be much friendlier if the message could show how to do it using the url scheme.

**Comment by ttscoff** [comment]
That error is from macOS, I have no control over it.

By the way, there's also a CLI available (simplifies using the url 
handler): https://bunchapp.co/docs/integration/cli/

-Brett
