### ISSUE TITLE
Bunch crashes sometimes when triggered with URL scheme

### ISSUE THREAD

**Issue by sleifer** [ttscoff/bunch#143]
I wrote a Stream Deck plugin that triggers open, close, or toggle of Bunches using the x-bunch url scheme.

Mostly everything works fine, but I've also seen Bunch crash when responding to an 'x-bunch://open'. I've attached a crash log.

Here's a sample config...
```
$ ~/bin/namedAppDirector Xcode-gm
$ ~/bin/namedAppDirector Xcode
!$ ~/bin/namedAppDirector Xcode-beta
Fork
%iTerm
Dash
Xcode-beta
!$ ~/bin/namedAppDirector Simulator
!$ ~/bin/namedAppDirector Kaleidoscope
```

namedAppDirector is a tool I wrote to quit an app by name matching.

[Bunch_2021-09-19-062436_SimBook.crash.zip](https://github.com/ttscoff/bunch/files/7192184/Bunch_2021-09-19-062436_SimBook.crash.zip)

**Comment by ttscoff** [comment]
Can I see a copy of namedAppDirector? The crash report points to a 
specific line in the script launching code that doesn't make a lot of 
sense. It would be helpful if I could try to perfectly replicate your 
setup.

-Brett

**Comment by sleifer** [comment]
Binary (lower case) and source (upper case) attached. It was written quickly a good while ago to get around issues at the time with multiple Xcodes installed. I've never bothered to look and see if there is a better solution now.
[namedAppDirector 2.zip](https://github.com/ttscoff/bunch/files/7192932/namedAppDirector.2.zip)
[NamedAppDirector.zip](https://github.com/ttscoff/bunch/files/7192933/NamedAppDirector.zip)
.

**Comment by ttscoff** [comment]
Huh, nope, that runs fine for me, via menu and via url handler. Can you 
narrow down a specific set of circumstances that consistently reproduce 
the crash?

-Brett

**Comment by sleifer** [comment]
I'll try. Nothing has so far leapt out at me. I think working correctly is most frequent. After that I sometimes get Bunch beach-balling for several seconds, and the rare crash. I'm sure you noticed in the crash log, but I want to call out that I'm on an M1 machine (iMac).

**Comment by ttscoff** [comment]
I do all my Bunch dev on an M1, so that part of our environment is the same. 

I'm not certain the crash has anything to do with namedAppDirector specifically at this point. It could just be a general error in the script launching code. The line that the crash log points to is just one where the PID for the NSTask is retrieved and stored. It's possible a null response just isn't being handled gracefully. Do you see the crash on other Bunches without namedAppDirector, and if so, do those also contain `$` shell lines?

**Comment by sleifer** [comment]
I have a bunch for a 'core' set of apps. I just opened and closed that repeatedly without issue (other than me being too fast for Mail occasionally being a bit slow to quit)

```
Mail
Safari
Reeder
Bear
iTerm
```

I then added the following call to another whipped up debug tool. No issues and I did open/close at least 10 times

```
$ ~/bin/arglogger this is from bunch
```

Finally I added the Xcode trio from the initial report and got a crash within 3 tries.

```
$ ~/bin/namedAppDirector Xcode-gm
$ ~/bin/namedAppDirector Xcode-beta
!$ ~/bin/namedAppDirector Xcode
```

I've attached the new crash log and the source for arglogger for completeness.

[Archive.zip](https://github.com/ttscoff/bunch/files/7195815/Archive.zip)

**Comment by ttscoff** [comment]
Yep, exact same line. I think that `namedAppDirector` may exit quickly 
enough that the task no longer has a PID by the time Bunch requests it. 
If you would, please download and run the pre-release beta build below. 
You can leave your stable build in place and just change the url handler 
to `x-bunch-beta://` to target only the beta build. Repeat the crashing 
test using that URL handler.

Download: http://ckyp.us/1MNLbL

-Brett

**Comment by sleifer** [comment]
I was going to change the url scheme used in my stream deck plugin, then I noticed its 'x-bunch://' calls were happily going to the beta build. Is using the beta scheme more more helpful to you or was it just to make having beta builds on the side easier?

I abusively opened and closed my xcode beta bunch and at first everything seemed to be going well but I did end up getting some crashes. It's possible the first one happened very shortly after the beta decided it was time to ask about automatically checking for updates but I'm not 100% certain of that. I did also get at least once where in the middle of the set of apps launching, the Bunch Beta beach-balled for several seconds.

A couple of crash logs from the beta are attached
[beta crash logs.zip](https://github.com/ttscoff/bunch/files/7196904/beta.crash.logs.zip)
.

**Comment by ttscoff** [comment]
Well, it's a different error now... unfortunately a significantly less useful one. These crashes are all inside of some opaque ARC retain/release cycle.

So on your side you've narrowed it down to just Bunches containing namedAppDirector calls and only when used on the Xcode trio? Or did your last test on the pre-release build expand to test other Bunches?

The `x-bunch-beta` scheme is just to force target the beta build if you have two installed. Otherwise it's just up to Launch Services to decide which handler it's going to trigger, which is unpredictable. But if the stable build isn't launching when you call the handler, no big deal.

**Comment by sleifer** [comment]
So far I have only tried the Beta with the Bunches I have for development with different version of Xcode. I will spend some time testing permutations to see if brings anything helpful to light.

**Comment by sleifer** [comment]
Small update...

I've played with 

```
Dash
!$ ~/bin/namedAppDirector Simulator
!$ ~/bin/namedAppDirector Kaleidoscope
```
 and

```
Dash
!$ ~/bin/namedAppDirector Kaleidoscope
```

Neither Simulator nor Kaleidoscope were ever running. I cycled between open and close quite quickly and lots of times trying to cause crashes, or hopefully not have one. Nothing close to normal use and quite abusive toward Bunch. I thought it was doing well, but I did get some crashes (not all of which I noticed in the moment). I also got a few times where Bunch beach-balled for a bit and then proceeded fine.
Attached are a few crash logs, maybe all the same thing, but I did not really explore them. and a sample run that hopefully caught some of what was going on during one of the beach ball incidents. I'm not certain which crashes go with which config other than the oldest is almost certainly the single namedAppDirector config and the newest is with the dual namedAppDirector config.
I'll continue exploring.
[crash logs and sample.zip](https://github.com/ttscoff/bunch/files/7207015/crash.logs.and.sample.zip)

**Comment by ttscoff** [comment]
Wow, there's a variety of crashers in here. How did you perform these 
tests, exactly? I'd love to be able to replicate some of these crashes 
while I have a debugger attached...

3 out of the 6 crash reports did have a common thread having to do with 
the menu refreshing after performing actions, so that's one I can debug 
a little more easily. It looks like the menu refresh call was generated 
from the AppleScript handler, so I should be able to force that.

-Brett

**Comment by sleifer** [comment]
I used by Stream Deck. I wrote a plugin that supports selecting Bunch config and choosing open, toggle, or close. So, I was quickly going back and forth between the button I set up for 'open dev', and 'close dev'. I haven't shared the plugin (yet?) but I'm happy to figure out how to bundle up and give you a copy if you have a Stream Deck and want it.

The plugin is using `NSWorkspace.shared.open` ...

```        switch action {
        case "open":
            url = URL(string: "x-bunch://open?bunch=\(bunch)")
        case "close":
            url = URL(string: "x-bunch://close?bunch=\(bunch)")
        case "toggle":
            url = URL(string: "x-bunch://toggle?bunch=\(bunch)")
        default:
            break
        }

        if let url = url {
            NSWorkspace.shared.open(url)
        }
```

**Comment by ttscoff** [comment]
Yeah, I'd love to play with the plugin on my Stream Deck if you care to 
share. Both for debugging this crash and out of curiosity :).

-Brett

**Comment by sleifer** [comment]
Let me know if there are any issues with the plugin. It's only been run in my own environment so far.

[com.droolingcat.bunch.streamDeckPlugin.zip](https://github.com/ttscoff/bunch/files/7244015/com.droolingcat.bunch.streamDeckPlugin.zip)

**Comment by isaacniebeling** [comment]
> Let me know if there are any issues with the plugin. It's only been run in my own environment so far.

_whistles inconspicuously while he downloads the plugin to try it out_
