### ISSUE TITLE
Support for Focus Modes in macOS Monterey

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#167]
This is a future feature request that I can't use (yet, but in December). 

I know that bunch has access to DND with `(dnd on)`. Can that be extended to focus modes.

Possible syntax could be `(focus <FOCUS NAME> on/off)`

**Comment by ttscoff** [comment]
I haven't dug into Monterey much yet beyond testing existing features, 
so I'll have to do some research on this one.

**Comment by nickwild-999** [comment]
I second this please

**Comment by ttscoff** [comment]
There's no API I can find that lets me easily set a focus mode by name, 
either from APIKit or with AppleScript. The easiest solution is to make 
a Shortcut that turns a specific focus mode on (or asks for input to 
select) and then trigger it with:

	$ /usr/bin/shortcuts run "[Shortcut Name]"

And maybe a second shortcut to end it on close:

	!$ /usr/bin/shortcuts run "[Shortcut Name]"

**Comment by lizard-heart** [comment]
How did I not think of that! I'll definitely use that obvious workaround; hopefully Apple adds an API for focus modes at some point.

**Comment by ttscoff** [comment]
Doubt it. They never did for Do Not Disturb, either. Apps that control that (including Bunch) have to use fairly hacky workarounds. I’m quite certain the hack would be significantly more complex for focus modes.

- Brett

**Comment by nickwild-999** [comment]
Thanks @ttscoff I was running this as applescript, but this is much more elegant. 
Thanks for Bunch, it is awesome!

**Comment by ttscoff** [comment]
FYI, there's now a `(shortcut NAME)` command that's a, er, shortcut to running `$ shortcuts run` and can take input and output.
