### ISSUE TITLE
"Embedded" Slack app launched instead of "main" one?

### ISSUE THREAD

**Issue by isaacniebeling** [ttscoff/bunch#168]
Today, when I ran my "Work" bunch, it fired up the app file from `~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/Slack 3305 1`, rather than the one from `/Applications`. I'm not aware of any changes in Slack or Bunch or the bunch file since I launched the bunch yesterday. However, I DID install a security patch for macOS at some point yesterday, and I don't recall if I launched the bunch after that point or not. I quit the bunch and relaunched it, and it still launched the deep app file (I'm not even sure what that's called, honestly, or whether that's sort of part of the `/Applications/Slack.app` installation, or something else completely?).

What should the expected behavior be here? Is there a recommendation on how to get it launching the "right" version of Slack again?

`Bunch Version 1.4.6 (132)`
`macOS Mojave 10.14.6` (yeah, it's old. i have my reasons. i'm trying to work past them :joy:)

**Comment by ttscoff** [comment]
Bunch is launching the requested app by name, so if some embedded app is 
responding to "Slack" before the main one, that's an issue at the system 
level. What happens if you open Script Editor and run `tell app "Slack" 
to activate`?

-Brett

**Comment by isaacniebeling** [comment]
If Slack is already running, it brings the running version to the foreground. 

The first time I tested when Slack was NOT running already was immediately after bringing Slack to the foreground via AppleScript as shown above and then quitting. THAT time, it launched the `/Applications` version. However, every time AFTER that has launched the `Library` version, including when quitting the `~/Library` version, manually opening the `/Applications` version (via Alfred), bringing it to the foreground with AppleScript, quitting, and then hitting the script again.

**Comment by ttscoff** [comment]
Ok. I'm not certain where your Library version came from, but it's definitely registered in launch services. I run Slack daily and I don't have a `~/Library/Containers/com.tinyspeck.slackmacgap` folder at all (though that is the correct bundle ID for the Slack app). I would suggest removing that folder. If it's actually vital to the operation of Slack, Slack will regenerate it automatically. HOWEVER, I'm not sure what preferences it might be storing in there. On my machine (also running Mojave), Slack doesn't put anything in ~/Library/Containers that I can find, and the actual preferences are stored in `~/Library/Preferences/com.tinyspeck.slackmacgap.plist`.

You might just move the Containers folder out to your Desktop and launch Slack again to see if all of your preferences persist. You could also just remove the `Slack 3305 1` binary from the nested folder. I can't imagine that's actually necessary for Slack to function. I could be wrong, though. It's a very weird setup that I'm entirely unsure of. All I know is that this rogue binary is registered with the system and has a high probability of hijacking the app name "Slack" or even the bundle id "com.tinyspeck.slackmacgap" if you launch with that.

**Comment by ttscoff** [comment]
Just in case you got an email version of my initial comment, note that I edited it to make sure I'm not suggesting moving the entire ~/Library/Containers folder anywhere, just the com.tinyspeck.slackmacgap folder.

**Comment by isaacniebeling** [comment]
I SUSPECT that it comes from, at some point, installing it via the mac app store, though I have no memory of doing so, and it doesn't APPEAR to be installed that way any more. From what I can tell, that's where sandboxed apps go. I'll go ahead and move some things around and see if that fixes things. Thanks for your help!

**Comment by isaacniebeling** [comment]
It's mostly weird that the registration changed somehow. ah well.

**Comment by isaacniebeling** [comment]
Quick late follow-up to say that I just ended up removing the sandboxed app and now all is well.
