### ISSUE TITLE
`open every` syntax error causes constant firing

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#169]
Is there a way to stop constant firings if a value is not properly set?

given the following bunch

```
---
open every: Thursday 15:00
toggles: false
---

drafts://x-callback-url/create?action=TWIC
Mimestream
```

This began to fire every second. I know the correction is `open on` instead of `open every`, but this seems like a mistake I will make more than once so I have to assume others will as well.

**Comment by ttscoff** [comment]
Yeah, I'll need to add some sanity checking. Seems like in a case like the "open every" key, it should only accept:

```
5m
5h
5h 30m
5:30
```

Anything value with a meridian or a day name (or any letters other than d, h, m, and s) should be rejected. That seems like it would cover the obvious, I think.

**Comment by ttscoff** [comment]
Added this sanity check for the next beta release. Scheduling is still flaky, have to dig further into it next.
