### ISSUE TITLE
How do I trigger a bash alias

### ISSUE THREAD

**Issue by beginnerninja** [ttscoff/bunch#172]
Hi,

I'm using latest Bunch Beta and I was trying to trigger a bash alias I have (lets call it myalias).

I tried this (errors for lack of recognition)
$ myalias

I also tried:

* <<EOFILE
#!/bin/bash
source ~/.bashrc
myalias
EOFILE

But the above doesn't work either.

Any suggestions/ideas?

**Comment by ttscoff** [comment]
Is there a reason you don't just put whatever the alias triggers directly into the script? Or run it as an executable script file?

Thanks!

Brett

**Comment by beginnerninja** [comment]
Hi Brett,

In the alias I conatenated to one of the files every time I ran the alias. However, you're right - I was lazy....so never mind. I'll close the ticket.

Thanks for your help.
