### ISSUE TITLE
Visual Studio Code does not open text and markdown files

### ISSUE THREAD

**Issue by beginnerninja** [ttscoff/bunch#182]
Hi,

I'm running the latest beta.

There is this closed issue with VS Code (https://github.com/ttscoff/bunch/issues/61) but I don't think this is it.

In my Bunch I tried both Code and Visual Studio Code via:
%Code
- /Users/foo/Dropbox/_nvalt_personal_notes/changelogx - test - 1234 Hare Dr, Some City, CA 12345 - 2021-12-06.1853.49.md
- /Users/foo/Dropbox/_nvalt_personal_notes/changelogx - 4567 Main - 2015-12-03.txt

In both cases I get an error message and log has:

2022-01-11 23:06:02: 🔴Application failed to launch (Code) and/or open file (/Users/foo/Dropbox/_nvalt_personal_notes/changelogx - test - 1234 Hare Dr, Some City, CA 12345 - 2021-12-06.1853.49.md)
2022-01-11 23:06:59: 🔴Application failed to launch (Code) and/or open file (/Users/foo/Dropbox/_nvalt_personal_notes/changelogx - 4567 Main - 2015-12-03.txt)

If I use iTerm and type:
code "/Users/foo/Dropbox/_nvalt_personal_notes/changelogx - 4567 Main - 2015-12-03.txt" it works fine and brings up the file up in VS Code (same with other file)

I'm not sure what I'm doing wrong.

Thanks!

**Comment by ttscoff** [comment]
I've had similar issues with Sublime Text. The easiest workaround is to 
just send the shell command instead of asking it to use the File->Open 
method.

$ code "/path/to/file"

-Brett

**Comment by beginnerninja** [comment]
@ttscoff - thanks - that works!
