### ISSUE TITLE
Failure when calling Timing by Applescript

### ISSUE THREAD

**Issue by mattsmallman** [ttscoff/bunch#194]
About 50% of the time I call Timing via AppleScript I get an error message and the whole bunch fails to load. It seems to occur most often from a 'cold start' i.e. I haven't used timing recently or if I have it was via a post. I'm using an M1 Pro MacBook if this makes a difference. If I close the bunch and reopen it invariably works. On occasions, Bunch crashes when doing this but not consistently. 

Command:
`* tell application "TimingHelper" to start timer with title "Automatically Started" project (project named "Daily Admin")`

Error:
`2022-02-02 08:24:29: 🔴{
    NSAppleScriptErrorNumber = "-1751";
}`

P.S. I love bunch and find it incredibly helpful as I intentionally switch between tasks.

**Comment by ttscoff** [comment]
Most of my Bunches start a Timing task, though usually with a Workflow I wrote rather than with AppleScript, but not entirely. I have 2 that use a similar script to yours. I've never had them error out (and certainly never crash). Have you tested repeatedly from Script Editor to see if you ever get the error outside of Bunch?

-Brett

**Comment by mattsmallman** [comment]
Some more observations:

1. The scripts are all fine in Script editor and never have a problem.
2. The call was at the bottom of the bunch after a few other scripts and applescripts:
- tell Moom call - Window Arrangement
- osascript call to custom script setting Ominfocus focus on a particular project 
3. I have moved to the top of the bunch for some bunches and don't experience the same issue.
4. For bunches I haven't moved the location of the line in they still crash occasionally.
5. For bunches I have moved the location of the line they still occasionally crash but I don't get the error - I think it must therefore be some time out or error handling of one of my other lines.

2 x crash logs attached:

1st produced error message and crashed after executing - timinghelper call at bottom
2nd crashed with no error message but did start Timing Task - timinghelper call at top

[Archive.zip](https://github.com/ttscoff/bunch/files/8022832/Archive.zip)

**Comment by ttscoff** [comment]
Just checking in as I let this slide for a few months... are you still seeing this issue? Have you found any other workarounds? Just want to catch up before I dig in and start testing again. If you're still using Bunch and still seeing the crashes, could you send me crash reports running the latest version?
