### ISSUE TITLE
Can't find Chrome?

### ISSUE THREAD

**Issue by seishonagon** [ttscoff/bunch#200]
I'm trying to open a few url's that work better in chrome, so I've tried to put just this in a bunch file, just like @ttscoff mentionned in a few issues here: 

```
Chrome
- (pause 3)
- {@n "https://www.integromat.com/xxx/nnnnnnn"}

```

This breaks bunch which tells me that I have an error -50 and crashes the app.

On the other hand: 
```
chrome:https://www.integromat.com/xxx/nnnnnnn
``` 
works perfectly well ! 
IT would be okay but I really need to use the workaround to open files in new tabs ...

Any ideas ?

**Comment by ttscoff** [comment]
Use “Google Chrome”

- Brett

**Comment by seishonagon** [comment]
Oh God, I'm an idiot. Thx.
