### ISSUE TITLE
Using the Caps Lock as a Hyper Key Does Not Respond as a Shortcut Modifier

### ISSUE THREAD

**Issue by bocciaman** [ttscoff/bunch#201]
The **Hyper Key (caps lock)** doesn't work for launching individual Bunches. I've tried the following methods for writing the text:
---
shortcut: @$~^o
---

**And**

---
shortcut: %o
---

The result is usually a warning Mac beep.

**Comment by ttscoff** [comment]
I'll have to test this. I usually use single characters as shortcuts, just FYI. Use the hyper key as the shortcut for Bunch, then launch an individual bunch with one letter (or shift-letter to double your options). That said, it should work, so will look into it.

**Comment by bocciaman** [comment]
Hi Brett,

Thanks for getting back to me. The issue was that I didn't have "a shortcut
to open the Bunch menu" before assigning a trigger to the actual Bunch. So
again, thank you!


Best,

-A.B. Anwar
YouTube Channel <https://bit.ly/2zp94dL> - My YouTube Channel
Inside That Ad <https://insidethatad.net> - My advertising blog
BocciaMan T-Shirt Store <https://teespring.com/stores/bocciamans-store> -
My T-Shirt Store

**Comment by ttscoff** [comment]
Cool, thanks for the update!
