### ISSUE TITLE
Menu not updating with conditionals

### ISSUE THREAD

**Issue by stevelw** [ttscoff/bunch#202]
More often then not the bunch menu isn't showing/hiding bunches based on their conditionals (ignore unless/if…). I then have to 'Refresh bunches' to update the menu.

V1.4.7
macOS 12.2.1

**Comment by ttscoff** [comment]
Is this still an issue for you? On build 139? I just tested toggling ignore if/unless on a test bunch a few times and it appeared and disappeared from the menu appropriately every time...

**Comment by stevelw** [comment]
Just tested on 143, still the same problem.

**Comment by stevelw** [comment]
If so toggle the setting, as you describe, it works. But if I open/close a bunch that another bunch is supposed to be watching for the menu doesn't update.

**Comment by ttscoff** [comment]
I need more explanation as to what you're doing. "a bunch that another bunch is supposed to be watching" is confusing me.
