### ISSUE TITLE
During installation, toolbar icon in the example screen doesn't match the actual toolbar icon

### ISSUE THREAD

**Issue by johnbernstein** [ttscoff/bunch#207]
During installation, toolbar icon in the example screen doesn't match the actual toolbar icon.

The attached screen shot illustrates the discrepancy.

<img width="288" alt="Screen Shot 2022-03-26 at 8 22 04 AM" src="https://user-images.githubusercontent.com/74948304/160246204-cc174bd1-d0e5-406e-ada0-8702c00df78c.png">

**Comment by ttscoff** [comment]
Ah, thank you. Forgot to update that when I updated the app icons.

Thanks,
Brett

**Comment by ttscoff** [comment]
Finally got around to updating this, both the popup background and the menu bar icon are updated for the next release.
