### ISSUE TITLE
FR: Get bunch status

### ISSUE THREAD

**Issue by isaacniebeling** [ttscoff/bunch#211]
I'd love to be able to get a bunch's status [1], particularly via URL handlers. My end goal is to be able to show a different icon on my Stream Deck for a running vs not-running bunch. I _think_ a URL handler would let me use something like BetterTouchTool or Keyboard Maestro, and I KNOW I could do it with a custom Stream Deck plugin [2]. I'm actually reasonably sure that, if a URL handler was there, I could just use the [StreamDeck API Request plugin](https://github.com/mjbnz/streamdeck-api-request) without custom-making something, too. 

Is this something that's feasible? I didn't see anything in the Integration docs for getting a bunch status, but maybe I'm just missing it.

[1] And maybe things like "all running bunches"? I don't have any use for it, but maybe others do...
[2] Actually, THAT would be a use case for "all bunches" -- then I could make a plugin that lets you select a bunch from a dropdown, and then toggle, start, or stop it, and change the icons as appropriate. It's pretty easy to call a URL from a plugin, but I think it's slightly harder to run a CLI script (I could theoretically just run `bunch -l` to get the list, but if I'm gonna make a plugin, I probably want to also be able to get the status, and we're back at square one, and just doing it ALL via URLs would be easier than having two different methods)

**Comment by isaacniebeling** [comment]
Update: Just saw the AppleScript `tell application "Bunch" to list open bunches` example; not sure how I missed it, but it's there. It'd still work better for my use case to get via a URL, and to get a specific bunch status, but I _might_ be able to make that work.

**Comment by ttscoff** [comment]
This can’t be done with the url handler as macOS url handler can’t return anything. It is, however, possible with the AppleScript library.

https://bunchapp.co/docs/integration/applescript/#list-all-bunches

You can use ‘list open bunches’ to get an array of open bunches, which you can compare to ‘list bunches’, the difference of which will give you closed bunches. Test if any given Bunch exists in the open bunches to get its status.

Thanks,
Brett

**Comment by isaacniebeling** [comment]
Dang. The advantage of something URL-based for the Stream Deck plugin, at least, is that it's pretty easy to run those on a timeout, so it's checking every `n` seconds. Oh well. I can probably come up with something. Thanks!

**Comment by ttscoff** [comment]
The zoom plugin for steam deck makes use of AppleScript, I know it’s feasible.

-Brett
________________________________

**Comment by isaacniebeling** [comment]
Yeah, I'll definitely look at that one, though I can't remember if that requires things to be compiled or if it can just be built as the standard javascripty plugin type. One way or another I'm pretty sure I can work it out. Heck, I can always put a whole PILE of bad ideas together and write some PHP code that calls osascript to get the list and then returns that info to the javascript from the Stream Deck :joy:

**Comment by isaacniebeling** [comment]
Just a quick note in case anyone finds this in the future: BetterTouchTool just added (alpha, as of today) support for Stream Decks, and using that and some minor modifications of your [BetterTouchTool-Widgets](https://github.com/ttscoff/BetterTouchTool-Widgets/) code (primarily, I had to manually change the UUIDs and tweak the JSON output to match the SD's expectations), I've been able to accomplish my goal -- showing a Bunch status on my Stream Deck. 🎉

**Comment by ttscoff** [comment]
Holy sh!t I missed that release. Will check it out after work. This is exciting!

**Comment by isaacniebeling** [comment]
It's definitely .... Alpha 😛 There's a ton of potential, but there are definitely still bugs -- mostly I'm running into issues when trying to put the same button on multiple profiles (I'm running it as a plugin, not having it take over completely). It's very cool, in any case.
