### ISSUE TITLE
Firefox: Open URLs in tabs instead of new windows

### ISSUE THREAD

**Issue by flegfleg** [ttscoff/bunch#212]
Hi, i could not get Firefox (or the Developer edition of FF) to open tabs… they all open in different (new) windows. 
I know Firefox is a bit problematic in regards to Mac automation, did anybody manage to solve this? 

My bunch: 
```
Firefox 
- http://start.local
- http://start.local/wp-admin/
```

**Comment by isaacniebeling** [comment]
Take a look at https://github.com/ttscoff/bunch/discussions/60 and https://github.com/ttscoff/bunch/discussions/145 -- you may be able to get some ideas there. I THINK I vaguely recall something about firefox and x-callback-urls that might ALSO be an option, but i don't remember for sure. If I get a chance to check my browser history, I'll post up :joy:

**Comment by flegfleg** [comment]
> Do you have Firefox set to open new windows in tabs? That can be set in Preferences, I believe. The catch is if you want some urls to open new windows, and others to open new tabs. 

Yes, it's set to open as tabs. I also do not need multiple windows. 
Thanks for the quick answer and your great app!
