### ISSUE TITLE
Bunch folder: space in name moves all bunches to submenu

### ISSUE THREAD

**Issue by Younghart** [ttscoff/bunch#242]
I just experimented with multiple Bunch folders and stumbled upon this fun little glitch: If there's a space in the folder name, all Bunches immediately get sent down the hierarchy. A picture says it best:
![Bunch_name_space](https://user-images.githubusercontent.com/2934471/183361239-fcef0e91-554d-4066-b15b-dfa243dc0487.png)

**Comment by ttscoff** [comment]
I've long run into glitches with folders containing spaces. I think I 
may have finally found the issue. Please grab beta 155 and see if it 
helps.

Also let me know if you have any trouble using the automatic update in 
Bunch Beta. I'm getting some weird behavior but I'm not certain there's 
not something wrong with my filesystem. I'm not sure which answer would 
be better :(...

-Brett
