### ISSUE TITLE
All my titles generate URL errors

### ISSUE THREAD

**Issue by ericwass** [ttscoff/bunch#253]
I'm just getting started with Bunch but on my first bunch I encountered an error that I can't fix: my bunch titles generate a weird "opening URL" error. I'm using the standard Frontmatter syntax. In fact I just copy/pasted from the example bunch provided. Yet, this happens on every single bunch I've tried to make. Everything generally works but Bunch throws this error that has to be dismissed. Thoughts?

<img width="267" alt="Screen Shot 2022-08-30 at 2 04 57 PM" src="https://user-images.githubusercontent.com/49699625/187543537-d92bc442-d50e-4cea-be36-b0145ba8433b.png">

Here is a sample Bunch that generates the above error:
```
---
title: Notion
---

@@

Notion
Drafts
Superhuman
```

**Comment by ttscoff** [comment]
Could you attach an actual copy of this Bunch so I can examine the file?

Thanks,
Brett

**Comment by ericwass** [comment]
Sure. I'm attaching two of them, both of which generate the errors. Thanks.
[Archive.zip](https://github.com/ttscoff/bunch/files/9457385/Archive.zip)

**Comment by ttscoff** [comment]
Oh, you have a blank line at the top of the files. The first `---` must 
be on the very first line.

**Comment by ericwass** [comment]
Ha. That was it. I didn't even notice there was a blank. Thank you. I'm excited to really dive in. Will be sending a donation shortly. Great work.
