### ISSUE TITLE
(hide desktop) fails, even on 1.4.11 (165)

### ISSUE THREAD

**Issue by jladicos** [ttscoff/bunch#255]
Hide desktop stopped working for me when I upgraded to the latest official release, so I tried the latest beta, and have the same issue. I created the following test bunch file:

```
---
title: Testing
---

(hide desktop)
```

When I run this bunch file, nothing happens except that a new Finder window is opened. Am I doing something wrong? The log says "Not quitting Finder".

Here is the log file.
 
[com.brettterpstra.BunchBeta 2022-09-09--23-18-41-521.log](https://github.com/ttscoff/bunch/files/9539171/com.brettterpstra.BunchBeta.2022-09-09--23-18-41-521.log)

### Update
Still not working, but I tried an experiment. After I hit the bunch, I relaunched the finder. After the relaunch, the desktop icons disappeared. When I toggled the bunch again, the desktop icons were still invisible until I relaunched the finder again.

Is there a System Preferences > Security & Privacy permission that is maybe missing?

**Comment by ttscoff** [comment]
Fixed for next update. Thanks for reporting.

**Comment by jladicos** [comment]
👋 Thanks for having a look and for the quick fix. You rock!
