### ISSUE TITLE
Remember open bunches

### ISSUE THREAD

**Issue by pahles** [ttscoff/bunch#260]
I have Remember open bunches checked in the Preferences. Whenever I restart my computer Bunch will always open all my bunches regardless of the fact that they were closed when I restarted. It does this with all the bunches except the Example bunch. What am I missing?

**Comment by ttscoff** [comment]
It shouldn't matter if you're properly restarting (not doing a hard 
shutdown) but does manually quitting Bunch with no Bunches open and then 
re-opening it still result in unopened Bunches re-opening?

**Comment by pahles** [comment]
Manually quitting Bunch with no bunches open and re-opening does not result in unopened Bunches re-opening. It only happens when properly restarting the computer. I had this on Catalina and now on Monterey too.

**Comment by ttscoff** [comment]
Only the Bunch that had been opened and then closed re-opened? So it's 
just not registering when Bunches close correctly?

-Brett

**Comment by pahles** [comment]
Yes, only the bunch that was opened en closed. Also true if multiple bunches were opened and closed, then all those bunches re-open after restarting Bunch.

**Comment by ttscoff** [comment]
Ok, uploading Beta build 168 in a little bit, please test and let me 
know if it solves the issue. (Currently only fixed in Bunch Beta, if 
you're not using that, please download from 
https://bunchapp.co/download/).

-Brett

**Comment by pahles** [comment]
This seems to be working! Had to set the path to my bunches again (none were shown, after setting the path again and restarting Bunch they were shown again).

Thanks for the fix!
