### ISSUE TITLE
Embedded shell scripts crash Bunch

### ISSUE THREAD

**Issue by ihatemornings** [ttscoff/bunch#264]
In the last version or two of the beta (I’m on 1.4.12, MacOS 12.5.1) launching a bunch with an embedded shell script crashes Bunch completely. The last line in the Bunch log is always something like:
```
2022-10-17 10:20:19: ⚪[Repro] Running Shell Script (/var/folders/fk/vd1l328107g4qbw01j0k7ywr0000gn/T/TemporaryItems/NSIRD_Bunch\ Beta_3gs1KN/C14F63DC-C939-41B8-AA50-AFBB2CA95B5F.sh)
```

The bunch I’m using to repro the bug is (minus the indentation – triple backticks in markdown code blocks are tricky!):
```
    $ ```
    #!/bin/zsh
    ```
```

This syntax also triggers the same crash:
```
<<EOFILE
#!/bin/zsh
EOFILE
```

As does this:
```
<<EOFILE
#!/bin/bash
EOFILE
```

Embedded shell scripts definitely used to work for me until a couple of beta versions ago.

**Comment by ttscoff** [comment]
Found the issue, new beta release forthcoming.

-Brett

**Comment by ihatemornings** [comment]
Thanks for the quick fix! My embedded shell scripts work again in version 1.4.12 (169).
