### ISSUE TITLE
List of bunches "disappear" from bunch menu when editing a bunch

### ISSUE THREAD

**Issue by seishonagon** [ttscoff/bunch#269]
This one is weird.
The bunch dock icon menu has a list of available bunches at the top, like so:

![screenshotnumberone](https://user-images.githubusercontent.com/6635078/200476070-fc623ef0-25fb-4b4f-a135-9ae4e7ed4818.jpeg)

But if I edit a bunch (e.g.: cmd-clicking on testing.bunch) and save it, the list of bunches ... disappears!:

![CleanShot Google Chrome-New Issue · ttscoffbunch2022-11-08 at 05 38 27@2x](https://user-images.githubusercontent.com/6635078/200476432-db5f80ee-5119-4c3a-b44e-543fd47734fb.png)

My editor is Nova, and I'm running Ventura 13.0 on an M1 MBP.

**Comment by ttscoff** [comment]
What version of Bunch?

- Brett

**Comment by seishonagon** [comment]
Sorry i'm late replying: holidays ...
Bunch Beta 1.4.12 (169)

**Comment by seishonagon** [comment]
Ha, seems build (170) sorted that one out?

**Comment by ttscoff** [comment]
Should have, I think.

- Brett
