### ISSUE TITLE
Bunch keyboard shortcut not detected if Bunch hidden by Bartender

### ISSUE THREAD

**Issue by Wildphinn** [ttscoff/bunch#277]
Title says it all: if Bunch is hidden by Bartender, it does not appear and does not show its menu upon pressing its shortcut. Moving it in the main menu bar restores all functionality. 

In case that helps: I'm on macOS 13, French locale. 

Thanks!

**Comment by ttscoff** [comment]
This is a known issue. You can either make Bunch always visible, or use the shortcuts in bartender preferences to bring the menu item forward and left click it.
