### ISSUE TITLE
Not authorized to send Apple events

### ISSUE THREAD

**Issue by lwd27** [ttscoff/bunch#281]
Under Ventura Bunch isn't able to call Moom to arrange the windows. The error is, "Not authorized to send Apple events to Moom."
![CleanShot 2022-12-13 at 14 06 19](https://user-images.githubusercontent.com/46834111/207435432-2c4a797f-8302-4fcf-8db4-b204c232e833.png)

Bunch Version 1.4.11 (166)
MacOS 13.1
M1 MacBook Air

**Comment by ttscoff** [comment]
I’m betting you’ll find this in security settings. Have you checked?

Thanks,
Brett

**Comment by lwd27** [comment]
Hi Brett,
Exactly right. Bunch had accessibility permissions, but I hadn’t noticed the System Events setting. All good now.

Thanks for the super-speedy response!

Regards,

Dan

**Comment by ttscoff** [comment]
Sure thing
