### ISSUE TITLE
Not authorized to send Apple events to System Events

### ISSUE THREAD

**Issue by kimonostereo** [ttscoff/bunch#282]
On beta Version 1.4.12 (170), I started seeing this error reported.
There was an error running an AppleScript, it's possible the target application does not respond to the requested command: "tell app "System Events" to set autohide of dock preferences to true"

I checked Privacy > Automations and Bunch is authorized.

The log shows: 
```
   NSAppleScriptErrorAppName = "System Events";
    NSAppleScriptErrorBriefMessage = "Not authorized to send Apple events to System Events.";
    NSAppleScriptErrorMessage = "Not authorized to send Apple events to System Events.";
    NSAppleScriptErrorNumber = "-1743";
    NSAppleScriptErrorRange = "NSRange: {28, 40}";
```

**Comment by ttscoff** [comment]
Try removing Bunch authorization and readding it manually using the + 
button. Let me know if that helps.

**Comment by kimonostereo** [comment]
Thank you! That seems to have fixed it. Have a great day!
