### ISSUE TITLE
Sometimes 2 versions of Bunch show up in the menu bar

### ISSUE THREAD

**Issue by kimonostereo** [ttscoff/bunch#285]
It doesn't seem to happen at first launch when I reboot, but after a while, Bunch will sometimes show two icons in the menu bar. When I go to Bunch > About Bunch for each, I get two different version numbers: 1.4.11 (166) and 1.4.12 (170). Not sure why I have two versions. I can quit each one individually, but when I re-launch Bunch, it opens both.

**Comment by ttscoff** [comment]
Do you have both Bunch and Bunch Beta installed?

-Brett

**Comment by kimonostereo** [comment]
As far as I can tell from searching, I only have Bunch Beta.

**Comment by ttscoff** [comment]
What are you using to launch? It makes zero sense that two versions 
would launch at once…

**Comment by kimonostereo** [comment]
Yeah that's what I think too! I'm using Alfred. See video.
If I launch Bunch Beta from the Applications folder, it only launches that one. Somehow Alfred launches 2 versions, but I can't find the non-beta version.

https://user-images.githubusercontent.com/175971/213016306-a84c300d-fcef-4d8f-9bae-86a1c738a44d.mp4

**Comment by ttscoff** [comment]
Run this in Terminal:

	mdfind 'kind:app Bunch'

-Brett

**Comment by kimonostereo** [comment]
It returned
`/Applications/Bunch Beta.app`

**Comment by ttscoff** [comment]
I have absolutely no idea what to tell you. It’s next to impossible that 2 instances, let alone instances with different version numbers, would lunch automatically, especially if only one app bundle exists on your drive. You’ve stumped me.

Thanks,
Brett

**Comment by kimonostereo** [comment]
Yeah same here! I tried uninstalling it and removing the Libraries and reinstalling it. Still launched two versions. 

Then I thought i'd quit the beta version and see if Activity Monitor could tell me where the other version was launching from. Looks like it was in: 
`/Users/scott/Library/Caches/com.brettterpstra.Bunch/org.sparkle-project.Sparkle/PersistentDownloads/BWKY6GXSb/Bunch 166/Bunch.app`

I deleted the entire folder in Caches and now it seems like just one launches as it should.

**Comment by ttscoff** [comment]
Sorry for the delay in responding to this. It appears that an update failed and it stored a downloaded copy in cache, which somehow got indexed by Spotlight and launched when calling Bunch from Alfred. Deleting the cache should definitely have cleared it up, but you obviously figured that out (nice sleuthing :)).
