### ISSUE TITLE
Apps won't quit - Sonarr / Radar

### ISSUE THREAD

**Issue by BillKeenan** [ttscoff/bunch#307]
Apps open fine, but won't close.

As simple as this in the bunch

Radarr
Sonarr

I've used the basic names, as well as the names pulled from plist,

they are based on the same code, so likely the same issue between them.

There's nothing in the bunch log,

**Comment by ttscoff** [comment]
Have you tried using the bundle identifier? I’m not familiar with either of these apps, so I can’t be certain what complexities there may be.

Thanks,
Brett

**Comment by BillKeenan** [comment]
```2023-11-08 11:15:35: ⚪[grabber] Open >>>>>>>>>>>>>>>>>>>>>
2023-11-08 11:15:35: ⚪[grabber] Launching app (com.osx.sonarr.tv)
2023-11-08 11:15:44: ⚪[grabber] Closing <<<<<<<<<<<<<<<<<<
2023-11-08 11:15:44: ⚪[grabber] Quitting app com.osx.sonarr.tv```

**Comment by ttscoff** [comment]
What Bunch does is actually closer to the AppleScript command "quit" than anything you would do from Terminal. Open up Script Editor and try:

```
tell app "Sonarr" to quit
```

And let me know what happens. I might have to install this app to figure out what's going on, but I've never even heard of it before.

**Comment by ttscoff** [comment]
I considered installing it to debug, but it's not codesigned, and THEN requires installing a PKG that's not codesigned. I'll avoid that hassle, thank you very much :).

**Comment by BillKeenan** [comment]
Yeah, that gets a timeout, I imagine the app is just kinda garbage..

**Comment by ttscoff** [comment]
Your best option is probably to send a killall shell command on quit. You might need to use ps to find the prices name, but it would something like

!$ killall Sonarr

- Brett

**Comment by RosemaryOrchard** [comment]
I'd recommend running these on a dedicated device alongside Plex and as docker containers. They're not designed to be started/shutdown regularly.
