### ISSUE TITLE
Documentation: frontmatter files do not seem to support tags but the documentation suggests they do

### ISSUE THREAD

**Issue by sylumer** [ttscoff/bunch#321]
First I create a sub folder (/directory) in my Bunches folder.

```
/Users/stephen/Documents/Bunches/Sub Folder
```

I then create a couple of bunch files in that folder with some test content.  

#### `b1.bunch`
```
---
Title: B-One
---

* say "Opening Bee One"

!* say "Closing Bee One"
```

#### `b2.bunch`
```
---
Title: B-Two
---

* say "Opening Bee Two"

!* say "Closing Bee Two"
```

If I then create a `folder.frontmatter` file in the same  folder and populate it with this content:

```
---
title: Title of the subfolder
tags: subftag1, subftag2
title prefix: 💧
---
```

When I view the menu bar list of bunches and tags, I can see "Title of the subfolder" as a sub folder for bunches and this contains two entries formatted exactly as I would expect.

![2024-02-10-10 29 44](https://github.com/ttscoff/bunch/assets/3868841/cb7a7b5c-b1e2-4549-b669-ae36ee212a29)

There is however no listing for the tags `subftag1` or `subftag2`

![2024-02-10-10 30 30](https://github.com/ttscoff/bunch/assets/3868841/cffa77d4-0828-4915-9e9e-32ab8ae08928)

I am using the beta version right now, so I tried a URL to see if it was just the listing and if the tags were being applied.

```
x-bunch-beta://toggle?tag=subftag1
```

Nothing happened, so it isn't just the UI.

[In the documentation for `folder.frontmatter`](https://bunchapp.co/docs/bunch-files/frontmatter/#folderfrontmatter), it says the following:

> A `folder.frontmatter `file is just a text file containing frontmatter keys and values. The keys `title`, `menu divider`, and `ignore` only affect the submenu item, and the key `shortcut` is always ignored. All other keys are applied to every Bunch in the folder.

But its looks to me like `tags` is not supported either.

Assuming I am correct in the above, I would like to suggest adding `tags` to the list of keys not supported by `folder.frontmatter` and explcitly calling out if you want to set tags on all bunches in a folder to see the setion on \@tag files a little further down the page.

**Comment by ttscoff** [comment]
Ok, you are correct that Bunch was removing `tags` frontmatter from folder.frontmatter keys. With the way the code currently functions, tag values in folder.frontmatter completely override tag values in individual Bunches. If I can figure out how to merge the two, I'll add the functionality back in. For now, just updating the documentation.
