### ISSUE TITLE
SOLVED: Changed Path Names not being recognised

### ISSUE THREAD

**Issue by stuzog** [ttscoff/bunch#329]
I've been wrestling with this for a while: if i change the path names of one or several files in a bunch, the new path name(s) are not recognised and I get a warning, one at a time, that bunch can't open them. It seems that bunch isn't updating properly after saving a bunch and refreshing bunches.

macOS Sonoma 14.4.1
bunch 1.4.17180

**Comment by ttscoff** [comment]
That's really odd, the Bunch should be read fresh on every parsing of the file. Can you show me an example with a little more detail, e.g. a working version and then the broken version of same? And have you tried quitting and restarting Bunch and getting the same issue?

**Comment by stuzog** [comment]
SOLVED: On wake-up this morning it showed errors that pointed to the need for an additional symbolic link to a directory of an external data drive. Adding this resulted in expected behavior. These errors were different from yesterday, so I'm just guessing that macOS Sonoma required time to completely clear the relevant caches. Duh!

**Comment by ttscoff** [comment]
Oh good :)

**Comment by RosemaryOrchard** [comment]
I had this issue once a while ago when Dropbox updated and changed the location—which is where my Bunch config is stored. So I was updating it on one machine, but it wasn't being synced to other locations. This also meant that I was editing the synced version and wondering why Bunch wasn't updating on my local machine 😂

**Comment by bryanemmanuelbasor** [comment]
> Oh good :)

**Comment by bryanemmanuelbasor** [comment]
> I've been wrestling with this for a while: if i change the path names of one or several files in a bunch, the new path name(s) are not recognised and I get a warning, one at a time, that bunch can't open them. It seems that bunch isn't updating properly after saving a bunch and refreshing bunches.
> 
> macOS Sonoma 14.4.1 bunch 1.4.17180
