### ISSUE TITLE
In Bunch Beta 1.4.0 (74) Preferences window can't be closed

### ISSUE THREAD

**Issue by moffat** [ttscoff/bunch#35]
Hi,

As it says in the subject line, when I open the preferences window in the latest beta, the "done" button does nothing, and it seems like the only way to close it is to quit the app.

Best.

**Comment by ttscoff** [comment]
Yep, sorry about that! B75 fixes and is out for automatic updates.

**Comment by ttscoff** [comment]
Oh man, and then I put out a release where it can only be dismissed once. New update forthcoming.

**Comment by ttscoff** [comment]
Ok, B76 is out and fixes this problem for real.
