### ISSUE TITLE
Preferences window unreadable

### ISSUE THREAD

**Issue by stuzog** [ttscoff/bunch#41]
![Bunch Preferences](https://user-images.githubusercontent.com/2623838/111524391-980f3e00-8719-11eb-9dc7-e96ee1cc347a.png)

Preferences window unreadable -- could be choice of Green for background? Green is a notoriously fickle colour as it often shows other colours like this.

Bunch Beta 1.4.0 (78) macOS 10.13.6 High Sierra, MacBook Pro Mid-2010 Gateway LCD monitor FHX2300bcmid 1920x1080 resolution DVI

**Comment by ttscoff** [comment]
Is your machine set to light or dark mode when this happens? The window should be using dark mode regardless, and the text should all be bright white, but something appears to not be registering that.

**Comment by ttscoff** [comment]
Could you try this build and let me know if the preferences look better? 

http://assets.brettterpstra.com/BunchBeta1.4.979-1.zip

They should appear like this no matter what the system light/dark mode is set to:

<img width="532" alt="CleanShot 2021-03-23 at 08 46 46@2x" src="https://user-images.githubusercontent.com/47833/112156533-51f02980-8bb4-11eb-93df-e579598c1371.png">

**Comment by ttscoff** [comment]
Oh, I just realized you're on 10.13. I'm not sure the dark mode setting will work prior to 10.14. Might have to rethink the background entirely.

**Comment by ttscoff** [comment]
Could you let me know if the latest build still has this issue for you? I'm in a position where I may have to drop support for 10.13 anyway, but if it's otherwise working for you in the latest builds, I might consider a workaround for just the preferences pane.
