### ISSUE TITLE
Bunches with toggling turned off are broken

### ISSUE THREAD

**Issue by mttjhn** [ttscoff/bunch#42]
Just upgraded to Bunch Beta 1.4.0 (78) and the `toggles: false` feature in frontmatter seems to be broken in this version. My bunches that used to work now just don't run. However, I'm able to remove that line from the frontmatter and they work just fine. Guessing something broke underneath the covers? 

Upon reviewing the log when I attempt to run the bunch, I get the following message: 
```
2021-03-19 08:54:29: ⚪[Work_Startup] Open >>>>>>>>>>>>>>>>>>>>>
2021-03-19 08:54:29: ⚪[Work_Startup] Closing <<<<<<<<<<<<<<<<<<
2021-03-19 08:54:29: ⚪[Work_Startup] Close after schedule removed
```

My bunch syntax frontmatter looks like this:

```
---
title: Work Startup
toggles: false
---
```

For now, I'm able to get them working by turning them back to "toggle" mode, but I have very specific things I want to do for my "startup" and "shutdown" bunches, so I like to have them NOT toggling...

**Comment by ttscoff** [comment]
Ah, I think I know how I might have broken this. It might be a few days before I have time to fix it, but I'll try to have an update out soon.

**Comment by ttscoff** [comment]
Yep, I think I have this fixed for the next update, will try to have it out this week if the other bugfixes go well,

**Comment by ttscoff** [comment]
Ok, b79 is out, please let me know if it fixes this issue.

**Comment by mttjhn** [comment]
Awesome, just tested it out and it appears to be working now. Thanks for the quick fix - I'm super grateful!
