### ISSUE TITLE
Bunch Beta 1.4 crash

### ISSUE THREAD

**Issue by brokosz** [ttscoff/bunch#43]
Per my email to you, @ttscoff:

I'm trying out the new Bunch 1.4 beta but it crashes on me. This is on an M1 MBA running Big Sur 11.2.3. I'm not really comfortable re-publishing the crash log here... The bunch file itself is pretty basic:

```
@@
%CotEditor
Couleurs
Fork
Pixelmator Pro
NotePlan 3
Discord

Finder
- XX
- <valid path>
- <valid path>

<valid url>
```

**Comment by ttscoff** [comment]
I'll get the crash log from your email, but just so you know there's no private information in one.

- Brett

**Comment by brokosz** [comment]
Ah - cheers

Brad

On Mar 20, 2021, at 18:31, Brett Terpstra ***@***.***> wrote:

﻿
I'll get the crash log from your email, but just so you know there's no private information in one.

- Brett

**Comment by ttscoff** [comment]
Is it only on this specific Bunch that you're getting the crash? This appears to be the same crash as an earlier issue, which just apparently resolved itself in the last couple of builds, but we never found the actual cause of it.

**Comment by brokosz** [comment]
The example.bunch crashed 1.4.0 (β78) as well. 👎🏼

**Comment by ttscoff** [comment]
Ok. Like I said, this bug has been really hard to track down, but I'll let you know if I come with more questions.

- Brett

**Comment by ttscoff** [comment]
The next update includes a major rewrite of some core functionality, so before I dig too deep into old code, I want to be sure that the new version doesn't already fix it. Could you donwload the build below and let me know if it helps with the issue?

http://assets.brettterpstra.com/BunchBeta1.4.078-2.zip

Also, a couple of reboots were involved with the last case of this bug disappearing, so if you haven't lately, please do that as a stupid debugging step.

**Comment by brokosz** [comment]
Progress! The beta above helped as did the reboot - I am able to successfully launch and toggle the example bunch. My custom bunch launches but gets hung up quitting apps when I toggle it off (according to the logs and the persistent yellow menubar icon).

I think another part of the crash issue is that until the reboot I was not prompted by Big Sur for privacy/automation based access to needed folders. Those showed up when I accessed paths for the first time post-reboot.

**Comment by brokosz** [comment]
I think my issue toggling the bunch off has something to do with the app state of something that gets launched. I'll keep playing with it. 

Trying a handful of other bunches with the new beta and everything works as expected. The parallel launch is crazy fast!

**Comment by ttscoff** [comment]
Are you running any scripts of any sort on close of the Bunch in question? Usually if it stops with the icon yellow, it's hung up waiting for a script to finish. I'd be curious what the log shows if you have it set to debug level.

**Comment by brokosz** [comment]
No, I'm not. I opened all the same apps as in the bunch and used the menu option to create a new bunch and it worked fine. I copied the app names back into the existing bunch that was working and now it's working as expected. I verified all the CFBundleNames... Nothing changed. ¯\_(ツ)_/¯ 



On Mar 23, 2021, at 07:25, Brett Terpstra ***@***.***> wrote:


Are you running any scripts of any sort on close of the Bunch in question? Usually if it stops with the icon yellow, it's hung up waiting for a script to finish. I'd be curious what the log shows if you have it set to debug level.

**Comment by ttscoff** [comment]
Weird. If you ever are able to recreate the issue, I'm definitely 
curious what was going on there.

Thanks,
Brett

**Comment by ttscoff** [comment]
> I think another part of the crash issue is that until the reboot I was not prompted by Big Sur for privacy/automation based access to needed folders. Those showed up when I accessed paths for the first time post-reboot.

Question on this... can you tell me exactly what kind of access was missing? Was it Accessibility permission, or did it actually need file access to specific folders? Bunch isn't sandboxed, so the latter shouldn't be the case, but if it is it might explain some of the crashes. 

Also, any idea which specific operation might have been failing because of lack of permissions? In most cases where it gets an error due to lack of permission, that should trigger the accessibility dialog. Would be great to figure out what's erroring out and NOT triggering the request.

**Comment by brokosz** [comment]
It was the folder access dialog, not just the entry Accessibility. Bunch wanted access to Documents, Desktop, etc. One of the Finder paths to open was in my Documents folder so that makes sense.

**Comment by ttscoff** [comment]
Ah yes, those special folders get a quarantine flag even if the app 
isn't sandboxed. I'll see if I can make that work a little smoother.

-Brett
