### ISSUE TITLE
A couple of bugs since the big rewrite

### ISSUE THREAD

**Issue by maxoriggi** [ttscoff/bunch#46]
Hello,
I have identified a couple of issues so far:
- apps marked with @ do not quit when a bunch quits
- apps marked with _ do not start when the bunch is marked for automatic launch at startup, but only when it's effectively launched at startup, if I open the bunch manually later on they start correctly.

**Comment by ttscoff** [comment]
Thanks for the report, I'll look into these. B82 just went out, but I didn't specifically address these in it. If it _does_ happen to fix them among all the other changes, let me know. More likely that it created bugs rather than fixed them, though...

**Comment by ttscoff** [comment]
One question: @Focus is designed to be used on an app that's already been launched. It doesn't actually register an app as launched in the Bunch on its own. Do you have a line prior to it that launches the app?

```
Reeder
@Reeder
```

If I test with that, it works fine for me. The reason it's set up like this is that for an app to "activate and hide other apps" it has to already be running. It's feasible that I could just interpret "@Reeder" to imply both lines on its own, so I'll look into that. For now the documentation [does mention this](https://brettterpstra.com/bunch-beta/docs/bunch-files/apps/#focus).

I can confirm the _ bug, will have to dig into that one. That's weird.

**Comment by maxoriggi** [comment]
Erm, no, I had it setup in a single line since forever, so never really checked the docs, my fault, but I can tell you that it worked fine this way till recently.
Yep, the _ bug is really strange, had to reboot a couple of times just to be sure.

**Comment by ttscoff** [comment]
I think I have the "_ bug" fixed for the next update, will do a little 
more testing first.

**Comment by ttscoff** [comment]
> Erm, no, I had it setup in a single line since forever, so never really checked the docs, my fault, but I can tell you that it worked fine this way till recently.

I may have changed the way @Focus operates during the big rewrite, so it's possible it was working up until then. The current method does a much better job of focusing, if used as the last line of a Bunch that's already launched the app in question.

**Comment by maxoriggi** [comment]
Great, I have already fixed my bunches :smile:
