### ISSUE TITLE
Application Finder failed to launch

### ISSUE THREAD

**Issue by ttscoff** [ttscoff/bunch#47]
Hey, this latest version broke items being opened with the finder. Error says "Application Finder failed to launch" and a dialog pops up complaining "Application "Service Station Finder Extension" failed to launch and/or open..." and then the file I was trying to open. The bunch has:

```
Finder
- SOMEFILE_I_WANT_TO_OPEN
```

I fixed it by calling the actual programs that finder would call to open the files.

_Originally posted by @moffat in https://github.com/ttscoff/bunch/discussions/38#discussioncomment-544533_

**Comment by ttscoff** [comment]
This appears to be an issue with the Service Station extension. Nothing changed in Bunch that should have caused any new problems like that.

Are you seeing this error at any other point in other apps?

Side note, you can use `Default` instead of `Finder` and it will open the file with whatever its default handler is, skipping the need for passing it through Finder first.

**Comment by moffat** [comment]
Mmmh actually the first time around the error dialog said something about the "setapp finder extension". Maybe a reboot will help...

**Comment by moffat** [comment]
All right, we can close this one. Relaunching the finder solved the issue. 

I need to become a better beta tester!

**Comment by ttscoff** [comment]
> I need to become a better beta tester!

LOL. You're one of the best beta testers because you break everything. That's basically the point :).

**Comment by moffat** [comment]
> > I need to become a better beta tester!
> 
> LOL. You're one of the best beta testers because you break everything. That's basically the point :).

I might have to add this to my CV.
