### ISSUE TITLE
FEATURE REQUEST: Navigate on Query Arrays/Multiple Choice Dialogs Options with Keyboard

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#52]
Similar to being able to activate bunches via keyboard shortcuts, could choosing Query Array options/Multiple Choice Dialogs be doable?

**To Test**:  Given the example

```
foo = ?[bar, biz, baz]

<<#${foo}
___

#[bar]
* say "Bar"

#[biz]
* say "Biz"

#[baz]
* say "Baz"
```

when bunch is called and popup menu appears it would be nice to be able to navigate between the options with the "Up/Down" keys. Currently I have to use the mouse to select the option.

**Comment by ttscoff** [comment]
On what OS? On Big Sur at least, when a dialog is presented it shows up floating, so it can't be covered up. It has initial key window status, so all keyboard shortcuts work. The only thing that would stop that is if another window takes focus. That's one of the reasons dialogs run before launching any other apps. Are you getting window focus?

Also, do you have All Controls enabled in System Preferences->Keyboard?

**Comment by kjaymiller** [comment]
OS: Big Sur
It's focusing on the window but you can't navigate through the selections. 

Didn't seen anything in System Preferences Keyboard
![CleanShot 2021-04-12 at 14 48 41](https://user-images.githubusercontent.com/8632637/114467256-8006cf00-9b9e-11eb-8b44-637f73d8a2a4.gif)

**Comment by ttscoff** [comment]
It's under System Preferences->Keyboard->Shortcuts at the bottom. On Big 
Sur it's labeled "Use keyboard navigation to move focus between 
controls." Let me know if that changes it for you, I'll make sure to add 
it to the docs.

-Brett

**Comment by kjaymiller** [comment]
Yup that was it!!! Thank you. I was definitely lookin in the wrong spot.
