### ISSUE TITLE
Upgrading Bunch Beta Launches a Bunch

### ISSUE THREAD

**Issue by moffat** [ttscoff/bunch#54]
As the subject lines says, I'm having an issue where every time bunch (beta) is upgraded, a particular bunch is run although it wasn't active when the upgrade process started.

**Comment by kjaymiller** [comment]
Can you show the log? (Open Bunch Menu and select CMD+Shift+L) there may be a bunch with startup set to true.

**Comment by moffat** [comment]
@kjaymiller Thanks! I was experimenting with the frontmatter settings and I accidentally left a startup setting on by mistake. Ok
