### ISSUE TITLE
Clear Checkmarks shortcut not working

### ISSUE THREAD

**Issue by rgonzalezayala** [ttscoff/bunch#62]
Hi: The shortcut for clearing checkmarks is not working. I closed all my applications, just if any of them were obstructing the functionality, but I need to click the option with my mouse to make it work.
Thank you.

![Screenshot of Bunch Beta (15052021 17-12-00)](https://user-images.githubusercontent.com/56691581/118379525-ae623a80-b5a0-11eb-80fa-cf0b11b84128.png)

![Screenshot of Google Chrome (15052021 17-05-57)](https://user-images.githubusercontent.com/56691581/118379462-2d0aa800-b5a0-11eb-9170-9da0657aa4f6.png)

**Comment by ttscoff** [comment]
Confirmed. I think the way I handle the Copy command for display windows is capturing the shortcut even with the additional modifiers. Will have to pick a different shortcut.

**Comment by rgonzalezayala** [comment]
Thanks!

Sent from my iPhone

On 17 May 2021, at 14:02, Brett Terpstra ***@***.***> wrote:

﻿
Confirmed. I think the way I handle the Copy command for display windows is capturing the shortcut even with the additional modifiers. Will have to pick a different shortcut.

**Comment by ttscoff** [comment]
Changed to Control-Option-Command-R for the next update, which I can verify works. Still not sure why the previous combo stopped working, but I couldn't seem to salvage it. Think I should rename the menu item to "Reset Checkmarks" to match the shortcut? Would that be less clear about what it does?

**Comment by rgonzalezayala** [comment]
Yes, of course. I think it would be.
Thank you very much!
Raul

Sent from my iPhone

On 20 May 2021, at 9:46, Brett Terpstra ***@***.***> wrote:

﻿
Changed to Control-Option-Command-R for the next update, which I can verify works. Still not sure why the previous combo stopped working, but I couldn't seem to salvage it. Think I should rename the menu item to "Reset Checkmarks" to match the shortcut? Would that be less clear about what it does?
