### ISSUE TITLE
Bunch & iTerm2 are not playing well together

### ISSUE THREAD

**Issue by jbeales** [ttscoff/bunch#66]
Maybe I have screwed up a permission somewhere, or it may be the iTerm beta, but recently iTerm hasn't been doing what Bunch asks it to. Here's the log entry with debug on:
```
2021-05-24 12:39:42: 🔴[4RoadService] {
    NSAppleScriptErrorAppName = "System Events";
    NSAppleScriptErrorBriefMessage = "Can\U2019t get process \"iTerm\".";
    NSAppleScriptErrorMessage = "System Events got an error: Can\U2019t get process \"iTerm\".";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {0, 0}";
}
```

At the moment I get the "Application iTerm failed to launch" message with iTerm Build 3.4.7beta2. A few days ago with an earlier beta I was getting the same message, but an iTerm window did open, but with no terminal in it.

If iTerm is running nothing happens to it. If it is not running it opens a window with a shell in my home directory, but does not open the directory I want.

The part of the bunchfile that should open iTerm is:

```
%iTerm
-XX
- ~/Work/4RoadService/laravelize
```

This is running Bunch Beta 102

**Comment by ttscoff** [comment]
I'll have to look further into this one. It seems to work fine if iTerm is NOT running when the Bunch opens, and you leave out the `XX`. New window is opened to the target directory. If it _is_ running, or if the `XX` is included, it gets an error handling the file opening.

The `%iTerm` line on its own works fine either way, so it's something screwy with the Apple Event used to send file open commands to it. Will dig into it this weekend.

**Comment by ttscoff** [comment]
(Here's too much explnation, you're welcome): So I had Bunch looking for the app name in running applications, and if it was found, changing the app name to match the localizedName property of the running application. In the case of iTerm, this was changing it to "iTerm2," as that was what iTerm was reporting as its localized name. However, it doesn't actually respond to that name for most purposes. As I'm not sure it accomplishes anything of real value, I'm just removing the function that made that change. In my testing with iTerm, this seems to fix the issue. Will need to do a little more testing to make sure it didn't break anything else before I release the update.

**Comment by jbeales** [comment]
Nice ;) I installed the update earlier - I'll let you know if there are problems.

**Comment by jbeales** [comment]
I'm going to resurrect this. I'm having the same trouble again, as described in [your May 27 comment](https://github.com/ttscoff/bunch/issues/66#issuecomment-850017510). While Bunch is waiting to open iTerm it seems to hang, so sometimes I'm waiting a long time for other apps to open.

**Comment by ttscoff** [comment]
Have you attempted to use applescript to open a new iTerm window rather than using file lines? I haven't tested this for a long time as I've never needed iTerm opened to a specific directory, but it does seem to be an issue with iTerm handling file open apple events.
