### ISSUE TITLE
Unable to run an app with a dot in the name

### ISSUE THREAD

**Issue by rgonzalezayala** [ttscoff/bunch#67]
Hi there.
I guess I found a bug because I can't run the application Raindrop.io within a bunch.
Perhaps it is due to the dot in the name.
Thanks.

**Comment by ttscoff** [comment]
I don't think it's the dot in the name. I grabbed Raindrop.io to test and NSWorkspace returns no app url when provided "Raindrop.io". I can get it via its bundle identifier, io.raindrop.macapp, though. This, however, highlighted a bug that didn't allow Bunch to accept bundle ids for launching apps, which is fixed for the next update.

I can't explain what Raindrop is doing that it wouldn't register with the system, but I can confirm that you can launch and quit it using the bundle id. Update coming soon.

**Comment by ttscoff** [comment]
Ok, the update is out and you should be able to launch/quit Raindrop.io using `io.raindrop.macapp`. That will work as a stopgap until I figure out why it won't launch by its name. Its weird because AppleScript can do it fine with `tell app "Raindrop.io" to launch`, so at least the Apple Events system recognizes it...

**Comment by rgonzalezayala** [comment]
Thank you very much!

On 28 May 2021, at 10:49, Brett Terpstra ***@***.***> wrote:


Ok, the update is out and you should be able to launch/quit Raindrop.io using io.raindrop.macapp. That will work as a stopgap until I figure out why it won't launch by its name. Its weird because AppleScript can do it fine with tell app "Raindrop.io" to launch, so at least the Apple Events system recognizes it...

**Comment by rgonzalezayala** [comment]
Hi Brett:
I am very sorry for bothering you so much; I guess that's the job of a beta tester.
Now I can run Raindrop.io, but I can't do it with Coherence X (Chrome) created apps.
I use Coherence X for Chrome-based apps like Skedpal 3 X, Notion, and Roam.

Thanks for your help.
__________________________________________________


On 28 May 2021, at 10:49, Brett Terpstra ***@***.***> wrote:


Ok, the update is out and you should be able to launch/quit Raindrop.io using io.raindrop.macapp. That will work as a stopgap until I figure out why it won't launch by its name. Its weird because AppleScript can do it fine with tell app "Raindrop.io" to launch, so at least the Apple Events system recognizes it...

**Comment by ttscoff** [comment]
You are correct, that's what beta tester's are expected to do. I truly appreciate it :).

This is another one where I'm not sure why macOS is having such a hard time recognizing the app by its name, but it works if you give it the bundle id. Eventually I'm going to have to figure this out more directly, but for right now I'd recommend the bundle ID path. Coherence creates a bundle id for each app based on the app name, so you'll have to dig in to find the one for each app. I made a quick app called "BrettTerpstra.com" and the bundle id was `com.BZG.CoherenceBrettTerpstra.com`. Using that in a Bunch launched and quit it properly.

You can find the bundle id by going into the App bundle and opening the `Info.plist`. Select the app in Finder, right click, and choose Show Package Contents. You'll see a folder called "Contents" and in that folder you'll find Info.plist. You should be able to open it in any text editor. Look for the line `<key>CFBundleIdentifier</key>` and the bundle id will be the next line, e.g. `<string>com.BZG.CoherenceBrettTerpstra.com</string>`.

If you want a faster way to do this repeatedly, I wrote [a little Ruby script](https://brettterpstra.com/2017/07/25/appinfo-get-app-details-quickly-in-terminal/) that will give you this (and other info) for any app. Instructions for installation and usage are in that post.

In the meantime I'll try to figure out a fallback for when macOS is convinced there's no such app installed.

**Comment by rgonzalezayala** [comment]
Hi Brett:
I found the following bundle ids within the info.plist files:
com.BZG.CoherenceSkedpal3_X
com.BZG.CoherenceRoam_Research_X
com.BZG.CoherenceNotion_X
I used them, and Bunch runs the three apps, but it doesn't quit them when toggled.
It's different with Raindrop.io. Bunch runs it and quits it.

Thanks for your help again.

Notion example:


__________________________________________________



On 29 May 2021, at 16:35, Brett Terpstra ***@***.***> wrote:


You are correct, that's what beta tester's are expected to do. I truly appreciate it :).

This is another one where I'm not sure why macOS is having such a hard time recognizing the app by its name, but it works if you give it the bundle id. Eventually I'm going to have to figure this out more directly, but for right now I'd recommend the bundle ID path. Coherence creates a bundle id for each app based on the app name, so you'll have to dig in to find the one for each app. I made a quick app called "BrettTerpstra.com" and the bundle id was com.BZG.CoherenceBrettTerpstra.com. Using that in a Bunch launched and quit it properly.

You can find the bundle id by going into the App bundle and opening the Info.plist. Select the app in Finder, right click, and choose Show Package Contents. You'll see a folder called "Contents" and in that folder you'll find Info.plist. You should be able to open it in any text editor. Look for the line <key>CFBundleIdentifier</key> and the bundle id will be the next line, e.g. <string>com.BZG.CoherenceBrettTerpstra.com</string>.

If you want a faster way to do this repeatedly, I wrote a little Ruby script <https://brettterpstra.com/2017/07/25/appinfo-get-app-details-quickly-in-terminal/> that will give you this (and other info) for any app. Instructions for installation and usage are in that post.

In the meantime I'll try to figure out a fallback for when macOS is convinced there's no such app installed.

**Comment by ttscoff** [comment]
Ok, I'm seeing the same issue. Also, do your coherence apps have a dot in their name? Because I found that if I create one without the dot, it does launch and quit, so it turns out the dot might actually be part of the problem after all. It doesn't make sense, but I'll look into that further.

**Comment by ttscoff** [comment]
Could you please test out this build and let me know if the issue is resolved: http://ckyp.us/tJhy1L

**Comment by rgonzalezayala** [comment]
Hi Brett.
No. They don't have a dot.
Regards,

Sent from my iPhone

On 30 May 2021, at 8:50, Brett Terpstra ***@***.***> wrote:

﻿
Ok, I'm seeing the same issue. Also, do your coherence apps have a dot in their name? Because I found that if I create one without the dot, it does launch and quit, so it turns out the dot might actually be part of the problem after all. It doesn't make sense, but I'll look into that further.

**Comment by rgonzalezayala** [comment]
Yes, of course.
I will let you know.

Sent from my iPhone

On 30 May 2021, at 9:58, Brett Terpstra ***@***.***> wrote:

﻿
Could you please test out this build and let me know if the issue is resolved: http://ckyp.us/tJhy1L

**Comment by rgonzalezayala** [comment]
Hi Brett:
Using the Finder application file names, Bunch runs the apps only if Chrome is not running. 
Perhaps it is not a regular performance because when I search the apps with Alfred, it runs them even if Chrome is running.

It quits them well whether Chrome is running or not.
Thank you very much.
__________________________________________________


On 30 May 2021, at 9:57, Brett Terpstra ***@***.***> wrote:


Could you please test out this build and let me know if the issue is resolved: http://ckyp.us/tJhy1L <http://ckyp.us/tJhy1L>

**Comment by ttscoff** [comment]
All right, so recap for me.

1. Launching Coherence apps using bundle ids launches but doesn't quit them
2. Launching using app names launches and quits but only launches if Chrome is not running

Do I have that right? Could you also test launching Raindrop.io by name and seeing if that one works any better with the test build?

**Comment by rgonzalezayala** [comment]
Hi Brett: I re tested and here is the recap:

Bundle Ids
	com.BZG.CoherenceRoam_Research_X
	com.BZG.CoherenceNotion_X
	com.BZG.CoherenceSkedpal3_X
	io.raindrop.macapp

Finder files names
	Roam Research X
	Notion X
	Skedpal3 X
	Raindrop.io


Testing with Bundle Ids
	Chrome running
		* All of them run
		* Only io.raindrop.macapp quits
	Chrome not running (results same as above)
		* All of them run
		* Only io.raindrop.macapp quits

Testing with file names
	Chrome running
		* Only Raindrop.io runs
		* Starting Roam, Notion and Skedpal3 manually
			- All of them quit
	Chrome not running
		* All of them run
		* All of them quit
	

Best regards.
Raul
__________________________________________________




On 30 May 2021, at 16:31, Brett Terpstra ***@***.***> wrote:


All right, so recap for me.

Launching Coherence apps using bundle ids launches but doesn't quit them
Launching using app names launches and quits but only launches if Chrome is not running
Do I have that right? Could you also test launching Raindrop.io by name and seeing if that one works any better with the test build?

**Comment by rgonzalezayala** [comment]
Hi Brett:

I think I found something interesting.
Using file names (I don't know how to use Bundle IDs), Keyboard Maestro works similarly to Bunch.

Testing with file names

Chrome running
	* Only Raindrop runs
	* Starting Roam, Notion, and Skedpal3 manually
		- All of them quit
Chrome not running
	* Only Raindrop and the first of the Coherence-based apps run.
	Starting the other Coherence-based apps manually
		- All of them quit

Considering that I am trying to run them sequentially in a Keyboard Maestro macro and Bunch runs the apps in parallel, the behavior is the same.
It sounds that, after all, using the last version you sent me, it is not a Bunch-related problem.
Wow.

Raul






__________________________________________________



On 30 May 2021, at 19:14, Raul Gonzalez ***@***.***> wrote:

Hi Brett: I re tested and here is the recap:

Bundle Ids
	com.BZG.CoherenceRoam_Research_X
	com.BZG.CoherenceNotion_X
	com.BZG.CoherenceSkedpal3_X
	io.raindrop.macapp

Finder files names
	Roam Research X
	Notion X
	Skedpal3 X
	Raindrop.io <http://raindrop.io/>


Testing with Bundle Ids
	Chrome running
		* All of them run
		* Only io.raindrop.macapp quits
	Chrome not running (results same as above)
		* All of them run
		* Only io.raindrop.macapp quits

Testing with file names
	Chrome running
		* Only Raindrop.io <http://raindrop.io/> runs
		* Starting Roam, Notion and Skedpal3 manually
			- All of them quit
	Chrome not running
		* All of them run
		* All of them quit
	

Best regards.
Raul
__________________________________________________




On 30 May 2021, at 16:31, Brett Terpstra ***@***.*** ***@***.***>> wrote:


All right, so recap for me.

Launching Coherence apps using bundle ids launches but doesn't quit them
Launching using app names launches and quits but only launches if Chrome is not running
Do I have that right? Could you also test launching Raindrop.io <http://raindrop.io/> by name and seeing if that one works any better with the test build?

**Comment by ttscoff** [comment]
Oh, yeah, I knew it wasn't specifically a Bunch problem, I was just 
hoping to find a way to work around it.

If you look at your processes when the Coherence-based apps are running 
with `ps ax`, you'll find that they all actually launch new instances of 
the same `Google Chrome Helper` binary inside of /Applications/Google 
Chrome.app with the Coherence bundle as the `--user-data-dir` argument, 
basically creating multiple sandboxed instances of the same app:

	5142   ??  S      0:00.61 /Applications/Google 
Chrome.app/Contents/Frameworks/Google Chrome 
Framework.framework/Versions/91.0.4472.77/Helpers/Google Chrome 
Helper.app/Contents/MacOS/Google Chrome Helper --type=utility 
--utility-sub-type=network.mojom.NetworkService 
--field-trial-handle=1718379636,5745574938738619291,3853985780927912614,131072 
--lang=en-US --service-sandbox-type=network --no-sandbox 
--user-data-dir=/Applications/Brett.app/Contents/Resources/../Profile 
--shared-files

Which means that as far as the system is concerned, once one instance of 
`Google Chrome Helper` is running (which Chrome also launches), the apps 
are all already running. That makes it a challenge to launch them using 
any NSWorkspace-based methods, which is what Bunch uses.

The test bundle I sent tries to circumvent that by falling back to 
finding the Coherence app bundles with Spotlight and handling them with 
more basic calls. Apparently even that is a bit tricky.

I even tested using AppleScript directly:

```
* tell app "Roam Research X" to launch
!* tell app "Roam Research X" to quit
```

If Chrome is running, the Coherence app still doesn't launch, and when 
close the bundle and run the AppleScript to quit the Coherence app, it 
actually quits Chrome. So this might actually be an impossible task.

I'll point out that Bunch can create basic SSBs on its own, though 
without the benefit of Chrome plugins or profiles. If you just use the 
`(display)` command, though, you can bring up a single-window, sandboxed 
version of a website, e.g. `(display https://brettterpstra.com)`. You 
can then use the parameters for [customizing the 
window](https://bunchapp.co/docs/bunch-files/commands/display/#window) 
to do all manner of sizing and positioning with it. It does a decent job 
of storing login cookies and what not as well. Might be worth playing 
with in this case.

-Brett

**Comment by rgonzalezayala** [comment]
Exactly. I noticed those instances of the Chrome Helper.

THANK you very much Brett!

Sent from my iPhone

On 31 May 2021, at 8:28, Brett Terpstra ***@***.***> wrote:

﻿
Oh, yeah, I knew it wasn't specifically a Bunch problem, I was just 
hoping to find a way to work around it.

If you look at your processes when the Coherence-based apps are running 
with `ps ax`, you'll find that they all actually launch new instances of 
the same `Google Chrome Helper` binary inside of /Applications/Google 
Chrome.app with the Coherence bundle as the `--user-data-dir` argument, 
basically creating multiple sandboxed instances of the same app:

5142 ?? S 0:00.61 /Applications/Google 
Chrome.app/Contents/Frameworks/Google Chrome 
Framework.framework/Versions/91.0.4472.77/Helpers/Google Chrome 
Helper.app/Contents/MacOS/Google Chrome Helper --type=utility 
--utility-sub-type=network.mojom.NetworkService 
--field-trial-handle=1718379636,5745574938738619291,3853985780927912614,131072 
--lang=en-US --service-sandbox-type=network --no-sandbox 
--user-data-dir=/Applications/Brett.app/Contents/Resources/../Profile 
--shared-files

Which means that as far as the system is concerned, once one instance of 
`Google Chrome Helper` is running (which Chrome also launches), the apps 
are all already running. That makes it a challenge to launch them using 
any NSWorkspace-based methods, which is what Bunch uses.

The test bundle I sent tries to circumvent that by falling back to 
finding the Coherence app bundles with Spotlight and handling them with 
more basic calls. Apparently even that is a bit tricky.

I even tested using AppleScript directly:

```
* tell app "Roam Research X" to launch
!* tell app "Roam Research X" to quit
```

If Chrome is running, the Coherence app still doesn't launch, and when 
close the bundle and run the AppleScript to quit the Coherence app, it 
actually quits Chrome. So this might actually be an impossible task.

I'll point out that Bunch can create basic SSBs on its own, though 
without the benefit of Chrome plugins or profiles. If you just use the 
`(display)` command, though, you can bring up a single-window, sandboxed 
version of a website, e.g. `(display https://brettterpstra.com)`. You 
can then use the parameters for [customizing the 
window](https://bunchapp.co/docs/bunch-files/commands/display/#window) 
to do all manner of sizing and positioning with it. It does a decent job 
of storing login cookies and what not as well. Might be worth playing 
with in this case.

-Brett

**Comment by rgonzalezayala** [comment]
Precisely because of this I am using Coherence:

I'll point out that Bunch can create basic SSBs on its own, though 
without the benefit of Chrome plugins or profiles.

Thanks again!

__________________________________________________


On 31 May 2021, at 8:28, Brett Terpstra ***@***.***> wrote:


Oh, yeah, I knew it wasn't specifically a Bunch problem, I was just 
hoping to find a way to work around it.

If you look at your processes when the Coherence-based apps are running 
with `ps ax`, you'll find that they all actually launch new instances of 
the same `Google Chrome Helper` binary inside of /Applications/Google 
Chrome.app with the Coherence bundle as the `--user-data-dir` argument, 
basically creating multiple sandboxed instances of the same app:

5142 ?? S 0:00.61 /Applications/Google 
Chrome.app/Contents/Frameworks/Google Chrome 
Framework.framework/Versions/91.0.4472.77/Helpers/Google Chrome 
Helper.app/Contents/MacOS/Google Chrome Helper --type=utility 
--utility-sub-type=network.mojom.NetworkService 
--field-trial-handle=1718379636,5745574938738619291,3853985780927912614,131072 
--lang=en-US --service-sandbox-type=network --no-sandbox 
--user-data-dir=/Applications/Brett.app/Contents/Resources/../Profile 
--shared-files

Which means that as far as the system is concerned, once one instance of 
`Google Chrome Helper` is running (which Chrome also launches), the apps 
are all already running. That makes it a challenge to launch them using 
any NSWorkspace-based methods, which is what Bunch uses.

The test bundle I sent tries to circumvent that by falling back to 
finding the Coherence app bundles with Spotlight and handling them with 
more basic calls. Apparently even that is a bit tricky.

I even tested using AppleScript directly:

```
* tell app "Roam Research X" to launch
!* tell app "Roam Research X" to quit
```

If Chrome is running, the Coherence app still doesn't launch, and when 
close the bundle and run the AppleScript to quit the Coherence app, it 
actually quits Chrome. So this might actually be an impossible task.

I'll point out that Bunch can create basic SSBs on its own, though 
without the benefit of Chrome plugins or profiles. If you just use the 
`(display)` command, though, you can bring up a single-window, sandboxed 
version of a website, e.g. `(display https://brettterpstra.com)`. You 
can then use the parameters for [customizing the 
window](https://bunchapp.co/docs/bunch-files/commands/display/#window) 
to do all manner of sizing and positioning with it. It does a decent job 
of storing login cookies and what not as well. Might be worth playing 
with in this case.

-Brett

**Comment by rgonzalezayala** [comment]
Hi Brett:

I found this idea:

Using the “open” command

One of OS X’s unique Terminal commands is the “open” command that allows you to handle files, programs, and URLs in sometimes unique ways. The benefit of this program is, similar to using the Terminal for directly launching an app in the “classic” way; however, it does have two benefits. First, it is easier to use, and second, it does not require the Terminal remain open:

open -a appname
In this command, replace “appname” with the name of your desired app, and it should launch. Note that by default this command will, similar to the OS X graphical environment, only open one instance of an app, so if the program is already open then this command will switch to it. However, you can use this command to open another instance of the program, by adding the “-n” flag:

open -n -a appname
Keep in mind that as with the classic approach, multiple instances of an application running at the same time under the same user account may have odd consequences with supporting services that the application uses; however, for simple programs and utilities it can be useful to run another instance as root, in order to overcome permissions limitations with your current user account. Also consider apps like the Calculator, where it might be useful to have more than one calculation going at a time.

URL: https://macissues.com/2015/02/06/how-to-launch-os-x-apps-via-the-terminal/ <https://macissues.com/2015/02/06/how-to-launch-os-x-apps-via-the-terminal/>

__________________________________________________

THE SAME WITH AN ADDITION:

Opening Mac OS X Applications from the Command Line
The Terminal command to launch OS X gui apps is appropriately called ‘open’ and here is how it works at it’s most simple:

open -a ApplicationName

That will open the defined app named “ApplicationName”.

But open is much more powerful than that. If you just type ‘open’ at the command prompt, you’ll return the basic help file with details on how to properly use the command with a variety of flags and syntax. While the open command exists in all versions of Mac OS X, the abilities vary somewhat depending on what version of OS X the Mac is running. Nonetheless, in modern releases this is what you’ll see:

$ open
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-b ] [-a ] [filenames] [--args arguments]
Help: Open opens files from a shell.
By default, opens each file using the default application for that file.
If the file is in the form of a URL, the file will be opened as a URL.
Options:
-a Opens with the specified application.
-b Opens with the specified application bundle identifier.
-e Opens with TextEdit.
-t Opens with default text editor.
-f Reads input from standard input and opens with TextEdit.
-F --fresh Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
-R, --reveal Selects in the Finder instead of opening.
-W, --wait-apps Blocks until the used applications are closed (even if they were already running).
--args All remaining arguments are passed in argv to the application's main() function instead of opened.
-n, --new Open a new instance of the application even if one is already running.
-j, --hide Launches the app hidden.
-g, --background Does not bring the application to the foreground.
-h, --header Searches header file locations for headers matching the given filenames, and opens them.

In other words, example simple command syntax could look like the following, opening “ApplicationName” with the file located at the path ‘/file/to/open’:

open -a ApplicationName /file/to/open

You’ll note you don’t need the full path to the application name, but you would need the full path to a file name.

URL: https://osxdaily.com/2007/02/01/how-to-launch-gui-applications-from-the-terminal/ <https://osxdaily.com/2007/02/01/how-to-launch-gui-applications-from-the-terminal/>

Regards,

__________________________________________________



On 31 May 2021, at 8:28, Brett Terpstra ***@***.***> wrote:


Oh, yeah, I knew it wasn't specifically a Bunch problem, I was just 
hoping to find a way to work around it.

If you look at your processes when the Coherence-based apps are running 
with `ps ax`, you'll find that they all actually launch new instances of 
the same `Google Chrome Helper` binary inside of /Applications/Google 
Chrome.app with the Coherence bundle as the `--user-data-dir` argument, 
basically creating multiple sandboxed instances of the same app:

5142 ?? S 0:00.61 /Applications/Google 
Chrome.app/Contents/Frameworks/Google Chrome 
Framework.framework/Versions/91.0.4472.77/Helpers/Google Chrome 
Helper.app/Contents/MacOS/Google Chrome Helper --type=utility 
--utility-sub-type=network.mojom.NetworkService 
--field-trial-handle=1718379636,5745574938738619291,3853985780927912614,131072 
--lang=en-US --service-sandbox-type=network --no-sandbox 
--user-data-dir=/Applications/Brett.app/Contents/Resources/../Profile 
--shared-files

Which means that as far as the system is concerned, once one instance of 
`Google Chrome Helper` is running (which Chrome also launches), the apps 
are all already running. That makes it a challenge to launch them using 
any NSWorkspace-based methods, which is what Bunch uses.

The test bundle I sent tries to circumvent that by falling back to 
finding the Coherence app bundles with Spotlight and handling them with 
more basic calls. Apparently even that is a bit tricky.

I even tested using AppleScript directly:

```
* tell app "Roam Research X" to launch
!* tell app "Roam Research X" to quit
```

If Chrome is running, the Coherence app still doesn't launch, and when 
close the bundle and run the AppleScript to quit the Coherence app, it 
actually quits Chrome. So this might actually be an impossible task.

I'll point out that Bunch can create basic SSBs on its own, though 
without the benefit of Chrome plugins or profiles. If you just use the 
`(display)` command, though, you can bring up a single-window, sandboxed 
version of a website, e.g. `(display https://brettterpstra.com)`. You 
can then use the parameters for [customizing the 
window](https://bunchapp.co/docs/bunch-files/commands/display/#window) 
to do all manner of sizing and positioning with it. It does a decent job 
of storing login cookies and what not as well. Might be worth playing 
with in this case.

-Brett

**Comment by ttscoff** [comment]
Have you tested at all with `open -n`? I imagine that could work for launching, but I'm not sure how to handle quitting the apps… maybe AppleScript would help?
