### ISSUE TITLE
Finder alert under Big Sur

### ISSUE THREAD

**Issue by maxoriggi** [ttscoff/bunch#70]
Hello,
since a couple of releases sometimes, when opening a bunch, I get a Finder alert telling me that app x is not open anymore, but everything still works correctly and app x (it isn't the same app every time) is effectively open.

**Comment by ttscoff** [comment]
Can you turn on debug messages in the log and get me a copy of the log when this happens? Use Help->Show Debug Log to open it in console.

**Comment by maxoriggi** [comment]
Here it is, I have started the same bunch 3 times and it showed the error once, the debug log doesn't say too much though:

2021-05-28 10:16:54: ⚪[App Dev] Open >>>>>>>>>>>>>>>>>>>>>
2021-05-28 10:16:54: ⚪[App Dev] Launching app (Tower) async 
2021-05-28 10:16:54: ⚪[App Dev] Launching app (Dash) async 
2021-05-28 10:16:54: ⚪[App Dev] Launching app (Xcode) async 
2021-05-28 10:16:54: 🔘Generating status menu
2021-05-28 10:16:58: 🔴Application Xcode failed to launch

I can say that Finder shows the application Xcode is not open anymore message immediately after launching, so the debug error shows up a little later and Xcode launches correctly anyway. It did happen with other bunches too, so it shouldn't be app or bundle specific (though it does not happen frequently so far). 
It did start after installing Big Sur, but there have been a couple of Bunch updates too, so it's difficult to track the source of the issue.

I'll keep the debug messages on and see if I can get further reports in the coming days.

**Comment by maxoriggi** [comment]
No, so far the bunches which have triggered the error do only launch apps.

**Comment by ttscoff** [comment]
I've made a change for the next update which moves input source checking to the main thread, which appears to have been the source of those crashes. I'm not sure why it was even running that if there were no input source commands, but let's see if that resolves the issue for you. I'll probably post that update today or tomorrow.

**Comment by ttscoff** [comment]
(deleted comment that went to the wrong thread).

This is a bit baffling as I haven't seen it happen at all with my own daily use. The "isn't open anymore" message should only appear if you're trying to quit an app, not when launching. I'll dig into the code a little bit and see if I can find anything that would trigger that.

**Comment by ttscoff** [comment]
Can you get me a screenshot of the Finder dialog?

**Comment by ttscoff** [comment]
I think I found a potential cause. I assume you're on Catalina or later?

**Comment by maxoriggi** [comment]
Yes, I'm on Big Sur and it started (some time) after installing it.
I'll try and get a screenshot when it happens again.

**Comment by ttscoff** [comment]
Please update to build 104 (Bunch->Check for Updates) and let me know if the problem still comes up.

**Comment by maxoriggi** [comment]
I have launched the problematic bunches a few times and so far the issue hasn't reappeared.

**Comment by maxoriggi** [comment]
Not so fast, now there is a problem with @ apps, on launch it seems ok, but on quit the app marked with @ does not get closed (I remember this bug showed up also many versions ago).

**Comment by ttscoff** [comment]
Is the app with @ also launched without the @? A focus command doesn't 
count as a launch command that would be reversed, so just checking.

**Comment by ttscoff** [comment]
Now _I'm_ getting that Finder dialog on the latest (104). Which will help me track it down...

**Comment by maxoriggi** [comment]
If I have both (in my case Mail and @Mail) all apps, including Mail, now get hidden.
If I leave only the focus command, Mail shows up correctly, but, clearly, it doesn't get closed later on.

**Comment by ttscoff** [comment]
Have you updated to the latest version? I walked back a change that would cause that first behavior.

- Brett

**Comment by maxoriggi** [comment]
Yes, version 105 fixes the regression.

**Comment by ttscoff** [comment]
Good to hear. I had hoped to make it do a better job of focusing apps 
when multiple apps were launching and sometimes the focused app would 
hide others before they showed their first window, in which case they 
wouldn't be hidden when the window showed. It got a bit overactive, 
though, and basically just launched everything as hidden, which 
obviously wasn't ideal. I might approach that problem again in the 
future, but for now I'll leave good enough alone.

Thanks,
Brett
