### ISSUE TITLE
[FEATURE REQUEST] Use clipboard contents as a variable

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#73]
Use the contents of the clipboard as a variable

```
---
title: say hello
---
* say hello ${clipboard}
```

Of course this would only work with the plaintext version of the contents.

I could see executing scripts this way with the content. And using bunch to execute the script saving it's output to a new variable and passing this output to another application.

**Comment by ttscoff** [comment]
I would think `variable = $ pbpaste` would do the trick… I mean, I could add a clipboard placeholder, but `pbpaste` seems like a simple solution. I'd have to test, but I think Bunch would even automatically trim whitespace/newlines for you.

**Comment by kjaymiller** [comment]
Definitely a fan of using what works. This is great for me!
