### ISSUE TITLE
Log when entering snippets

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#75]
This is a suggestion purely for debugging purposes...

If you have your logger set to `Debug Messages`, you do not get a notification showing that the bunch has entered a snippet. 

```
## Test Snippet
---
title: Test Embedded Snippet
---

<<#Test
___
---[Test]
(log this is a test)
```

## Test Results (Log)
2021-05-30 22:07:58: ⚪[Tests/test_embedded_snippet] Open >>>>>>>>>>>>>>>>>>>>>
2021-05-30 22:07:58: ⚪[Tests/test_embedded_snippet] Processing command "log this is a test"
2021-05-30 22:07:58: 🟡[Tests/test_embedded_snippet] Logger: this is a test

**Comment by ttscoff** [comment]
This isn't really feasible with the current architecture. When reading a Bunch file, Bunch parses for Snippet items, reads in the content of the specified snippet, and replaces the snippet item with the content. By the time it gets to executing, it's treating the Snippet contents as just part of the main Bunch. This allows apps and commands launched inside the snippet to be quit/reversed as if they were part of the main Bunch, among other benefits, but also means that Bunch has no idea at runtime what came from a snippet and what was just part of the main Bunch.

But I have to ask, why isn't just including a `(log Beginning Snippet)` command good enough for debugging?

**Comment by kjaymiller** [comment]
I am currently using the `(log Beginning Snippet)` as a test point but it was more of interesting point that I wonder may have ben an oversight.

More wanted to raise the question in case it hadn't been thought of.
