### ISSUE TITLE
Conditionals Not Correctly Logging `if var`

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#76]
The documentation points to testing existence with `if var_1`
<img width="752" alt="CleanShot 2021-05-30 at 23 03 36@2x" src="https://user-images.githubusercontent.com/8632637/120147290-46fcdb00-c19b-11eb-882f-ab25e69f26bd.png">

When I've tried this the conditional moves to else every time where a value exists or not.

## Test Bunch
```
---
title: Test Conditional Empty Variable
---

(log emptyValue=${emptyValue})

if emptyValue
    (log in if emptyValue=${emptyValue}!)
    ${emptyValue}
else
    (log in else, emptyValue=${emptyValue})
end
---
```

**Comment by ttscoff** [comment]
As it currently stands, `if var` is a "truthy" test. If $var starts with T or Y, it passes, if it starts with anything else, it should fail. There isn't currently a test just to see if a variable exists and return true. 

I should either adjust the handling of `if VAR` to test for existence, or make the documentation more clear. Open to thoughts on this one.

**Comment by ttscoff** [comment]
Of course, now that I say this and test it, setting emptyValue to "true" doesn't actually pass the test either. I'll look into that.

**Comment by ttscoff** [comment]
Found it, case sensitivity bites me again. Ok, back to the original response: `if VarName` will only return true if $VarName starts with T or Y (case insensitive). I can see that returning true if the variable has any content at all, though, and false if it's undefined (like `-z` tests in the shell), so let me know your opinion on that.

**Comment by kjaymiller** [comment]
My initial though was if the value was _explicitly_ `false` or `undefined`, the condition would return `false`.

**Comment by ttscoff** [comment]
I agree. Will consider empty value a negative for the next update. Thanks!

**Comment by ttscoff** [comment]
Wait, though. Does that mean if $Var is set to "any content", does it return true simply because it exists and isn't empty/false, or does it need to be "true" to pass?

**Comment by ttscoff** [comment]
Ok, here's my thought:

Return false if VarValue is:
- undefined
- "false" or "no"
- 0 or any negative number

Return true if VarValue:
- has any content that's NOT "false", "no" or a number <=0

That seems most in line with other scripting languages handling of variable tests with no comparisons.

**Comment by kjaymiller** [comment]
The only thought on this would be the `a number <=0` my scripting is mostly Python but

```python
if -1: # Evaluates as True
  ...
```

This however this could cause confusion as 

```python
-1 == True  # or if -1 is true in bunch
>> False
```

**Comment by ttscoff** [comment]
Yeah, I guess Ruby is the same, `if -1` evaluates to true. And I guess 
that if you were testing the return value of a script, it would be 
POSITIVE integers that evaluated to errors.

So what we're saying is that any numeric value should evaluate to true 
unless its tested as a comparison, right? So in the case of `if 
VarName`, if VarName were any number, it would be true.

**Comment by ttscoff** [comment]
I believe this is all sorted in the latest version, please re-open if you still see any issues.
