### ISSUE TITLE
Issue when referencing Filemaker Pro in a bunch

### ISSUE THREAD

**Issue by andre-alp** [ttscoff/bunch#77]
I'm trying to activate / deactivate Filemaker Pro 18 Advanced in a bunch file:

If I refer to it as 'FileMaker Pro Advanced' then Bunch cannot open the application.  However, if I start the application ('outside' Bunch) then, when I deactivate the Bunch, the application will close.

If I refer to it as 'FileMaker Pro 18 Advanced' then the opposite happens; Bunch will open the application, but on deactivating the Bunch the application will not close - and I see "Tried to quit app, but app not running (FileMaker Pro 18 Advanced)" in the log file.

**Comment by ttscoff** [comment]
Oh, I blanked on bundle ids. You could try using the bundle identifier instead of the app name. These take a little work to discover, but I have a pretty [easy-to-install script](https://brettterpstra.com/2017/07/25/appinfo-get-app-details-quickly-in-terminal/) that makes it painless (when it works). You can also locate it by just looking inside the App Bundle at `/Applications/FileMaker Pro 18 Advanced.app/Contents/Resources/Info.plist`, under the key `CFBundleIdentifier`.

Once you have the bundle id, you can use it instead of the app name in Bunch. I _think_ that might help with the fact that it responds to two different names.

**Comment by ttscoff** [comment]
I've added special handling for this case in build 109 (just released). Like I said, I don't have FileMaker to test, so let me know if it solves it. You should be able to just use:

```
FileMaker Pro 18 Advanced
```

It should be able to both launch and quit using that name.

I also added (for future cases) a (slightly clumsy) syntax for quitting an app on close without launching it on open. Use a "triple negative," i.e. three exclamation points, to quit an app when closing. Combine with a `%` ignore and you can launch and quit using different names:

```
%FileMaker Pro 18 Advanced
!!!FileMaker Pro Advanced
```

Like I said, this particular case should already be handled, but the `!!!` functionality should make it easier to deal with these anomolies if more cases arise.

**Comment by andre-alp** [comment]
The first solution you suggested (below) works perfectly:
```
%FileMaker Pro 18 Advanced
!* tell app "FileMaker Pro Advanced" to quit
```

Using solution 2 (Bundle ID), FileMaker opens, but refuses to close. In the log I see:
```
2021-06-12 21:19:09: ⚪[fmptest2] Open >>>>>>>>>>>>>>>>>>>>>
2021-06-12 21:19:09: ⚪[fmptest2] Launching app (com.filemaker.client.pro12)
2021-06-12 21:19:09: 🔘Generating status menu
2021-06-12 21:19:24: ⚪[fmptest2] Closing <<<<<<<<<<<<<<<<<<
2021-06-12 21:19:24: 🟡[fmptest2] Tried to quit app, but app not running (com.filemaker.client.pro12)
2021-06-12 21:19:24: 🔘Generating status menu
```

Solution 3 (Build 109) exhibits interesting behaviour.  I can use either "FileMaker Pro 18 Advanced" or "FileMaker Pro Advanced" as the application name - and FileMaker will open.  But it will not close.

If I use the '!!!' syntax, like this:
```
%FileMaker Pro 18 Advanced
!!!FileMaker Pro Advanced
```
then Filemaker opens, but on closing the bunch, not only does FileMaker keeps running - but I see two log entries telling me that Bunch is trying to *start* Filmaker:
```
2021-06-12 21:35:25: 🔘Generating status menu
2021-06-12 21:35:40: ⚪[fmptest3] Open >>>>>>>>>>>>>>>>>>>>>
2021-06-12 21:35:40: ⚪[fmptest3] Launching app (FileMaker Pro 18 Advanced)
2021-06-12 21:35:54: ⚪[fmptest3] Closing <<<<<<<<<<<<<<<<<<
2021-06-12 21:35:54: ⚪[fmptest3] Launching app FileMaker Pro Advanced
2021-06-12 21:35:54: ⚪[fmptest3] Launching app FileMaker Pro Advanced
2021-06-12 21:35:54: 🔘Generating status menu
```

So, solution 1 solves the immediate problem for me (and huge thanks for that!).  Am more than happy to keep testing future releases with FMPro / VSCode if it's of help.

Thanks again

**Comment by andre-alp** [comment]
You mentioned that 'the 18 is going to change eventually'.  It already has - the current version of FMPro is 19, and I imagine 20 is on the horizon.

However, the BundleID for my version 18 is ```com.filemaker.client.pro12```.   Version 12 was the last release with a change to the file format that FMPro uses, and versions 12 to 18 all use the same '.fmp12' file extension.  

Could it be that FileMaker use the same BundleID across successive versions (until there's a backwards incompatible release)?

**Comment by ttscoff** [comment]
Are you using the very latest version? !!! won't work on anything but the latest.

Thanks,
Brett

**Comment by andre-alp** [comment]
I'm using Bunch Beta 1.4.0 (109)

**Comment by ttscoff** [comment]
Weird. I'll have to test that again.

Thanks,
Brett

**Comment by andre-alp** [comment]
My mistake, sorry.

I have two machines here, one running Big Sur, and the other still on High Sierra (can't upgrade, long story).  I was testing on the wrong machine :(

The '!!!' syntax works perfectly on Big Sur, just not on High Sierra.

Using the BundleID on Big Sur still yields the same results as mentioned yesterday; FMP opens, but fails to close.  Log says:
```
2021-06-13 17:14:18: ⚪[fmpro2] Open >>>>>>>>>>>>>>>>>>>>>
2021-06-13 17:14:18: ⚪[fmpro2] Launching app (com.filemaker.client.pro12)
2021-06-13 17:14:23: ⚪[fmpro2] Closing <<<<<<<<<<<<<<<<<<
2021-06-13 17:14:23: 🟡[fmpro2] Tried to quit app, but app not running (com.filemaker.client.pro12)
```
Sorry to waste your time.  Am duly mortified.
- Andre

**Comment by ttscoff** [comment]
The high Sierra machine is also running the latest version of Bunch? There's no reason I can think of that !!! would only work on Big Sur…

- Brett

**Comment by andre-alp** [comment]
Yes, absolutely. The identical version of Bunch running on both.
Anything else I could do to help you get to the bottom of this?

**Comment by ttscoff** [comment]
That's really odd. I can verify that `!!!` is working perfectly on Big Sur, but I don't currently have a working install of anything earlier to try to debug on. I'll see if I can find anything theoretically off in the code...
