### ISSUE TITLE
Force bunch open only works when called via x-callback

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/bunch#91]
Having a bunch that runs a bunch that is already open generates an - `Bunch (BUNCHNAME) already open` message and the bunch is not triggered again.

You can get around this by calling the bunch via an x-callback-url (or setting toggle: true) but is there a way to do this with just referencing the bunch? Perhaps a flag could make it so that the bunch will always open again?

**Comment by ttscoff** [comment]
Try setting `ignores state: true` instead of "toggles." Let me know if 
that helps.

-Brett

**Comment by kjaymiller** [comment]
That's a new one! I did more testing and it appears that if the app closes the associated bunch will also close.

```
🔘Generating status menu
2021-07-02 08:33:52: ⚪[zoom] Closing <<<<<<<<<<<<<<<<<<
2021-07-02 08:33:52: 🔴[zoom] Tried to close Headphones, which does not toggle
2021-07-02 08:33:52: ⚪[zoom] Quitting app Zoom
2021-07-02 08:33:52: 🔴App not running (Zoom)
2021-07-02 08:33:52: 🔘Generating status menu
```

This works for me. Thanks!
